"use client";
import { useMemo, useState } from "react";
import { createCharacter } from "@/app/actions";
import { calculateMaxChakra, getAbilityModifier, getProficiencyBonus, pointBuyCost, pointBuyTotal, skills, standardArray } from "@/lib/rules";
type Ability = "str" | "dex" | "con" | "int" | "wis" | "cha";
const abilities: Ability[] = ["str", "dex", "con", "int", "wis", "cha"];
const names: Record<Ability,string> = {str:"St\u00e4rke",dex:"Geschicklichkeit",con:"Konstitution",int:"Intelligenz",wis:"Weisheit",cha:"Charisma"};
const short: Record<Ability,string> = {str:"STR",dex:"GES",con:"KON",int:"INT",wis:"WEI",cha:"CHA"};
const skillNames: Record<string,string> = {Acrobatics:"Akrobatik",AnimalHandling:"Tierf\u00fchrung",Arcana:"Arkane Kunde",Athletics:"Athletik",Deception:"T\u00e4uschung",History:"Geschichte",Insight:"Motivation",Intimidation:"Einsch\u00fcchterung",Investigation:"Nachforschungen",Medicine:"Heilkunde",Nature:"Naturkunde",Perception:"Wahrnehmung",Performance:"Auftreten",Persuasion:"\u00dcberzeugen",Religion:"Religion",SleightOfHand:"Fingerfertigkeit",Stealth:"Heimlichkeit",Survival:"\u00dcberleben"};
const steps = ["Grundlagen","Attribute","Fertigkeiten","Chakra","Jutsu","Kampf","\u00dcbersicht"];
const label = (x:string) => x.replaceAll("_"," ").toLowerCase().replace(/(^| )\S/g,c=>c.toUpperCase());
const signed = (x:number) => `${x >= 0 ? "+" : ""}${x}`;
type State = {name:string;level:number;background:string;alignment:string;description:string;mode:"MANUAL"|"STANDARD_ARRAY"|"POINT_BUY";scores:Record<Ability,number>;array:Record<Ability,number|null>;saving:string[];skill:string[];nature:string;reservoir:string;regen:string;control:string;jutsu:string[];speed:number;maxHp:number;acOverride:string};
const initial:State = {name:"",level:1,background:"",alignment:"",description:"",mode:"MANUAL",scores:{str:10,dex:10,con:10,int:10,wis:10,cha:10},array:{str:null,dex:null,con:null,int:null,wis:null,cha:null},saving:[],skill:[],nature:"",reservoir:"AVERAGE",regen:"TRAINED",control:"TRAINED",jutsu:[],speed:30,maxHp:10,acOverride:""};
export default function Creator({campaignId,natures,jutsu}:{campaignId:string;natures:{key:string;displayName:string}[];jutsu:{id:string;name:string;rank:string;chakraCost:number;range:string;actionType:string;natures:{nature:{key:string;displayName:string}}[]}[]}) {
 const [step,setStep]=useState(0); const [s,setS]=useState<State>(initial); const patch=(p:Partial<State>)=>setS(v=>({...v,...p}));
 const setScore=(a:Ability,v:number)=>patch({scores:{...s.scores,[a]:v}}); const assign=(a:Ability,v:string)=>{const n=v?Number(v):null;patch({array:{...s.array,[a]:n},scores:{...s.scores,[a]:n??10}})};
 const used=Object.values(s.array).filter((v):v is number=>v!==null); const available=standardArray.filter(v=>!used.includes(v)); const compatible=useMemo(()=>jutsu.filter(x=>x.natures.some(n=>n.nature.key===s.nature)),[jutsu,s.nature]); const max=calculateMaxChakra(s.level,s.scores.con,s.scores.wis,s.reservoir as never); const remaining=27-pointBuyTotal(abilities.map(a=>s.scores[a])); const go=(n:number)=>setStep(Math.max(0,Math.min(6,n)));
 const change=(a:Ability,d:number)=>{const n=s.scores[a]+d;if(n<8||n>15)return;const scores={...s.scores,[a]:n};if(pointBuyTotal(abilities.map(k=>scores[k]))<=27)setScore(a,n)}; const canUp=(a:Ability)=>s.scores[a]<15&&pointBuyTotal(abilities.map(k=>({...s.scores,[a]:s.scores[a]+1})[k]))<=27;
 return <main className="shell narrow"><a href={`/campaign/${campaignId}`} className="back"> Kampagne</a><div className="eyebrow">CHARAKTERERSTELLUNG</div><h1>Gestalte deinen Shinobi.</h1><nav className="creator-steps" aria-label="Fortschritt">{steps.map((x,i)=><button type="button" className={i===step?"active":""} onClick={()=>i<=step&&go(i)} key={x}>{i+1}. {x}</button>)}</nav><form action={createCharacter.bind(null,campaignId)} className="panel form"><input type="hidden" name="mode" value={s.mode}/><input type="hidden" name="name" value={s.name}/><input type="hidden" name="level" value={s.level}/><input type="hidden" name="background" value={s.background}/><input type="hidden" name="alignment" value={s.alignment}/><input type="hidden" name="description" value={s.description}/><input type="hidden" name="speed" value={s.speed}/><input type="hidden" name="maxHp" value={s.maxHp}/><input type="hidden" name="acOverride" value={s.acOverride}/><input type="hidden" name="nature" value={s.nature}/><input type="hidden" name="reservoir" value={s.reservoir}/>{abilities.map(a=><input type="hidden" name={a} value={s.scores[a]} key={a}/>)}{s.saving.map(x=><input type="hidden" name="savingThrow" value={x} key={x}/>)}{s.skill.map(x=><input type="hidden" name="skill" value={x} key={x}/>)}{s.jutsu.map(x=><input type="hidden" name="jutsu" value={x} key={x}/>)}
 {step===0&&<><h2>Grundlagen</h2><p className="muted">Name und Stufe sind erforderlich. Die brigen Angaben sind optional.</p><label>Name<input required value={s.name} onChange={e=>patch({name:e.target.value})}/></label><label>Stufe<input type="number" min="1" max="20" value={s.level} onChange={e=>patch({level:Number(e.target.value)})}/></label><label>Hintergrund<input value={s.background} onChange={e=>patch({background:e.target.value})}/></label><label>Ausrichtung<input value={s.alignment} onChange={e=>patch({alignment:e.target.value})}/></label><label>Beschreibung<textarea value={s.description} onChange={e=>patch({description:e.target.value})}/></label></>}
 {step===1&&<><h2>Attribute</h2><div className="segmented">{(["MANUAL","STANDARD_ARRAY","POINT_BUY"] as const).map(x=><button type="button" className={s.mode===x?"selected":""} onClick={()=>patch({mode:x})} key={x}>{x==="MANUAL"?"Manuell":x==="STANDARD_ARRAY"?"Standardwerte":"Punktekauf"}</button>)}</div>{s.mode==="STANDARD_ARRAY"?<><p className="muted">Nicht zugewiesene Werte: {available.length?available.join(", "):"keine"}</p><div className="ability-grid">{abilities.map(a=><label key={a}>{short[a]}  {names[a]}<select value={s.array[a]??""} onChange={e=>assign(a,e.target.value)}><option value="">Wert whlen</option>{[...new Set([...(s.array[a]?[s.array[a]]:[]),...available])].map(v=><option value={v} key={v}>{v} ({signed(getAbilityModifier(v))})</option>)}</select><small>Modifikator {signed(getAbilityModifier(s.scores[a]))}</small></label>)}</div></>:s.mode==="POINT_BUY"?<><p className="points-remaining">Verbleibende Punkte: {remaining} / 27</p><div className="point-buy-grid">{abilities.map(a=><div className="score-control" key={a}><strong>{names[a]}</strong><span>{short[a]}</span><div><button type="button" disabled={s.scores[a]<=8} onClick={()=>change(a,-1)} aria-label={`${names[a]} senken`}></button><b>{s.scores[a]}</b><button type="button" disabled={!canUp(a)} onClick={()=>change(a,1)} aria-label={`${names[a]} erhhen`}>+</button></div><small>Modifikator {signed(getAbilityModifier(s.scores[a]))}  Kosten {pointBuyCost(s.scores[a])}</small></div>)}</div></>:<><p className="muted">Manuelle Werte folgen den normalen Kampagnen-Grenzen.</p><div className="ability-grid">{abilities.map(a=><label key={a}>{short[a]}  {names[a]}<input type="number" min="1" max="20" value={s.scores[a]} onChange={e=>setScore(a,Number(e.target.value))}/><small>Modifikator {signed(getAbilityModifier(s.scores[a]))}</small></label>)}</div></>}</>}
 {step===2&&<><h2>Fertigkeiten</h2><p className="muted">Whle bis zu 3 Fertigkeiten, die deinen Hintergrund und deine Ausbildung widerspiegeln.</p><p className="points-remaining">Gewhlte Fertigkeiten: {s.skill.length} / 3  bungsbonus {signed(getProficiencyBonus(s.level))}</p><div className="prof-grid"><section><h3>Rettungswrfe</h3><div className="compact-grid">{abilities.map(a=>{const k=a.toUpperCase();return <label className="check" key={k}><input type="checkbox" checked={s.saving.includes(k)} onChange={()=>patch({saving:s.saving.includes(k)?s.saving.filter(x=>x!==k):[...s.saving,k]})}/><span>{names[a]}</span></label>})}</div></section><section><h3>Fertigkeiten</h3><div className="compact-grid">{Object.entries(skills).map(([skill,a])=>{const selected=s.skill.includes(skill);const mod=getAbilityModifier(s.scores[a.toLowerCase() as Ability])+ (selected?getProficiencyBonus(s.level):0);return <label className="check" key={skill}><input type="checkbox" checked={selected} disabled={!selected&&s.skill.length>=3} onChange={()=>patch({skill:selected?s.skill.filter(x=>x!==skill):[...s.skill,skill]})}/><span>{skillNames[skill]??skill}<small>{a.toUpperCase()}  {signed(mod)}</small></span></label>})}</div></section></div></>}
 {step===3&&<><h2>Chakra</h2><label>Primre Chakra-Natur<select required value={s.nature} onChange={e=>patch({nature:e.target.value,jutsu:[]})}><option value="">Eine Natur whlen</option>{natures.map(n=><option key={n.key} value={n.key}>{n.displayName}</option>)}</select></label><label>Reservoir<select value={s.reservoir} onChange={e=>patch({reservoir:e.target.value})}>{["VERY_LOW","LOW","AVERAGE","HIGH","VERY_HIGH","EXCEPTIONAL","MONSTER"].map(x=><option key={x}>{label(x)}</option>)}</select></label><label>Chakra-Regeneration<select value={s.regen} onChange={e=>patch({regen:e.target.value})}>{["NOVICE","TRAINED","ADVANCED","EXPERT","MASTER"].map(x=><option key={x}>{label(x)}</option>)}</select></label><label>Chakra-Kontrolle<select value={s.control} onChange={e=>patch({control:e.target.value})}>{["NOVICE","TRAINED","ADVANCED","EXPERT","MASTER"].map(x=><option key={x}>{label(x)}</option>)}</select></label><div className="preview"><small>MAXIMALES CHAKRA</small><strong>{max}</strong></div></>}
 {step===4&&<><h2>Jutsu</h2><p>Gewhlt: {s.jutsu.length} / 2</p>{compatible.length===0&&<div className="empty"><p>Whle zuerst eine Chakra-Natur.</p></div>}{compatible.map(x=><label className="check jutsu-choice" key={x.id}><input type="checkbox" checked={s.jutsu.includes(x.id)} disabled={!s.jutsu.includes(x.id)&&s.jutsu.length>=2} onChange={()=>patch({jutsu:s.jutsu.includes(x.id)?s.jutsu.filter(y=>y!==x.id):[...s.jutsu,x.id]})}/><span><strong>{x.name}</strong><small>Rang {x.rank}  {x.chakraCost} Chakra  {x.actionType}  {x.range}</small></span></label>)}</>}
 {step===5&&<><h2>Kampf</h2><label>Bewegung<input type="number" min="0" value={s.speed} onChange={e=>patch({speed:Number(e.target.value)})}/></label><label>Maximale TP<input type="number" min="1" value={s.maxHp} onChange={e=>patch({maxHp:Number(e.target.value)})}/></label><label>Rstungsklasse berschreiben<input value={s.acOverride} onChange={e=>patch({acOverride:e.target.value})} placeholder="Optional"/></label><p className="muted">Initiative, bungsbonus und die Standard-Rstungsklasse werden automatisch abgeleitet.</p></>}
 {step===6&&<><h2>\u00dcbersicht</h2>{[["Grundlagen",0],["Attribute",1],["Fertigkeiten",2],["Chakra",3],["Jutsu",4],["Kampf",5]].map(([title,target])=><section className="review-section" key={String(title)}><div className="section-heading"><h3>{title}</h3><button type="button" className="button ghost" onClick={()=>go(Number(target))}>Bearbeiten</button></div>{title==="Attribute"?<div className="review-grid">{abilities.map(a=><span key={a}>{short[a]}  {names[a]}<strong>{s.scores[a]} ({signed(getAbilityModifier(s.scores[a]))})</strong></span>)}</div>:title==="Kampf"?<div className="review-grid"><span>Maximale TP<strong>{s.maxHp}</strong></span><span>Bewegung<strong>{s.speed}</strong></span><span>Initiative<strong>{signed(getAbilityModifier(s.scores.dex))}</strong></span><span>bungsbonus<strong>{signed(getProficiencyBonus(s.level))}</strong></span><span>Rstungsklasse<strong>{s.acOverride||10+getAbilityModifier(s.scores.dex)}</strong></span></div>:title==="Chakra"?<div className="review-grid"><span>Natur<strong>{natures.find(n=>n.key===s.nature)?.displayName||"Nicht gewhlt"}</strong></span><span>Reservoir<strong>{label(s.reservoir)}</strong></span><span>Maximales Chakra<strong>{max}</strong></span></div>:<p>{title==="Grundlagen"?`${s.name||"Nicht angegeben"}  Stufe ${s.level}`:title==="Fertigkeiten"?`${s.skill.length} / 3 gewhlt`:title==="Jutsu"?`${s.jutsu.length} Jutsu gewhlt`:""}</p>}</section>)}<button className="button primary" type="submit">Charakter erstellen </button></>}
 <div className="creator-nav">{step>0?<button type="button" className="button ghost" onClick={()=>go(step-1)}> Zurck</button>:<span/>}{step<6?<button type="button" className="button primary" onClick={()=>go(step+1)}>Weiter </button>:<span/>}</div></form></main>;
}



