import {describe,expect,it} from "vitest";
import {calculateMaxChakra,calculateShortRestChakraRecovery,canRemoveNature,effectiveAc,getAbilityModifier,getChakraExhaustionState,getDeathSaveMode,getLimitBreakHpCost,longRestState,limitBreakBonus,preserveChakra,savingThrowModifier,shortRestState,skillModifier,getProficiencyBonus} from "./index";
describe("extended D&D rules",()=>{it.each([[4,2],[5,3],[8,3],[9,4],[17,6]])("proficiency %i",(l,b)=>expect(getProficiencyBonus(l)).toBe(b));it.each([[8,-1],[10,0],[11,0],[12,1],[20,5]])("ability %i",(s,m)=>expect(getAbilityModifier(s)).toBe(m));it("saving throws and skills",()=>{expect(savingThrowModifier(14,5,"NONE")).toBe(2);expect(savingThrowModifier(14,5,"PROFICIENT")).toBe(5);expect(skillModifier(14,5,"NONE")).toBe(2);expect(skillModifier(14,5,"PROFICIENT")).toBe(5);expect(skillModifier(14,5,"EXPERTISE")).toBe(8);expect(effectiveAc(14)).toBe(12);expect(effectiveAc(14,18)).toBe(18)})});
describe("extended Chakra",()=>{it.each([[1,10,10,"AVERAGE",170],[2,14,12,"HIGH",240],[1,16,18,"VERY_HIGH",275]])("max Chakra",(l,c,w,r,m)=>expect(calculateMaxChakra(l,c,w,r as never)).toBe(m));it("preserves full, partial, clamps",()=>{expect(preserveChakra(100,100,120)).toBe(120);expect(preserveChakra(50,100,120)).toBe(50);expect(preserveChakra(120,120,80)).toBe(80)});it.each([[51,"NORMAL"],[50,"STRAINED"],[26,"STRAINED"],[25,"EXHAUSTED"],[11,"EXHAUSTED"],[10,"CRITICALLY_EXHAUSTED"],[1,"CRITICALLY_EXHAUSTED"],[0,"CHAKRA_EMPTY"]])("exhaustion %i",(c,s)=>expect(getChakraExhaustionState(c,100).key).toBe(s));it.each([["NOVICE",10],["TRAINED",15],["ADVANCED",20],["EXPERT",25],["MASTER",35]])("recovery %s",(r,p)=>expect(calculateShortRestChakraRecovery(100,r as never)).toBe(p))});
describe("extended rests",()=>{it("short rest restores, removes wound, and limits",()=>{expect(shortRestState(1,20,100,180,"TRAINED",0)).toMatchObject({currentHp:20,currentChakra:125,shortRestsSinceLongRest:1,severelyWounded:false});expect(shortRestState(0,20,100,180,"TRAINED",1).shortRestsSinceLongRest).toBe(2);expect(()=>shortRestState(0,20,100,180,"TRAINED",2)).toThrow()});it("long rest resets state",()=>expect(longRestState(10,200)).toEqual({currentHp:10,currentChakra:200,shortRestsSinceLongRest:0,limitBreakUsed:false,severelyWounded:false,deathSaveSuccesses:0,deathSaveFailures:0}))});
describe("extended death and Limit Break",()=>{it("death modes and limit costs",()=>{expect(getDeathSaveMode(34,100)).toBe("ADVANTAGE");expect(getDeathSaveMode(33,100)).toBe("NORMAL");expect(getDeathSaveMode(1,100)).toBe("NORMAL");expect(getDeathSaveMode(0,100)).toBe("DISADVANTAGE");expect(getLimitBreakHpCost("D")).toBe(5);expect(getLimitBreakHpCost("C")).toBe(10);expect(getLimitBreakHpCost("B")).toBe(20);expect(getLimitBreakHpCost("A")).toBe(35);expect(getLimitBreakHpCost("S")).toBe(50)});it("Limit Break HP and bonus metadata",()=>{expect(Math.max(0,10-getLimitBreakHpCost("S"))).toBe(0);expect(limitBreakBonus("ATTACK",null)).toBe("ADVANTAGE");expect(limitBreakBonus(null,"DEX")).toBe("+2 SAVE DC");expect(limitBreakBonus(null,null)).toBeNull()})});
describe("nature invariants",()=>{it("requires secondary nature for removal",()=>{expect(canRemoveNature(true,2)).toBe(false);expect(canRemoveNature(false,1)).toBe(false);expect(canRemoveNature(false,2)).toBe(true)})});


