"use server";
import { GameSessionStatus, JutsuLibraryAccess, LocationType, JutsuOrigin, JutsuRank } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/prisma";
import { requireCampaign } from "@/lib/session";
import { z } from "zod";

const text = (fd: FormData, key: string) => String(fd.get(key) ?? "").trim();
const customSchema=z.object({name:z.string().trim().min(1),rank:z.nativeEnum(JutsuRank),chakraCost:z.coerce.number().int().min(0),description:z.string().trim().min(1),japaneseName:z.string().trim().optional(),range:z.string().trim().optional(),duration:z.string().trim().optional(),actionType:z.string().trim().optional(),attackType:z.string().trim().optional(),damageDice:z.string().trim().optional(),damageType:z.string().trim().optional(),saveAbility:z.string().trim().optional(),requiresConcentration:z.boolean().default(false)});
const ids=(fd:FormData,key:string)=>fd.getAll(key).map(String).filter(Boolean);
async function customData(campaignId:string,fd:FormData){const parsed=customSchema.parse({name:text(fd,"name"),rank:text(fd,"rank"),chakraCost:text(fd,"chakraCost"),description:text(fd,"description"),japaneseName:text(fd,"japaneseName")||undefined,range:text(fd,"range")||undefined,duration:text(fd,"duration")||undefined,actionType:text(fd,"actionType")||undefined,attackType:text(fd,"attackType")||undefined,damageDice:text(fd,"damageDice")||undefined,damageType:text(fd,"damageType")||undefined,saveAbility:text(fd,"saveAbility")||undefined,requiresConcentration:fd.get("requiresConcentration")==="on"});const natureIds=ids(fd,"natureIds"),prerequisiteIds=ids(fd,"prerequisiteIds");const validNatures=await prisma.chakraNature.count({where:{id:{in:natureIds}}});if(validNatures!==natureIds.length)throw new Error("Ungültige Chakra-Natur");if(prerequisiteIds.includes(String(fd.get("id")??"")))throw new Error("Ein Jutsu kann nicht sich selbst voraussetzen");const available=await prisma.jutsu.findMany({where:{id:{in:prerequisiteIds},OR:[{campaignId:null},{campaignId}]},select:{id:true}});if(available.length!==new Set(prerequisiteIds).size)throw new Error("Ungültige oder fremde Voraussetzung");return {parsed,natureIds,prerequisiteIds};}
const customSlug=(name:string)=>name.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,100)||"custom-jutsu";
export async function createCustomJutsu(campaignId:string,fd:FormData){await requireCampaign(campaignId,true);const {parsed,natureIds,prerequisiteIds}=await customData(campaignId,fd);let slug=customSlug(parsed.name);if(await prisma.jutsu.findFirst({where:{campaignId,slug}}))slug=`${slug}-${Date.now().toString(36)}`;const j=await prisma.jutsu.create({data:{campaignId,slug,name:parsed.name,japaneseName:parsed.japaneseName||null,description:parsed.description,rank:parsed.rank,chakraCost:parsed.chakraCost,range:parsed.range||"Self",duration:parsed.duration||"Instantaneous",actionType:parsed.actionType||"Action",attackType:parsed.attackType||null,damageDice:parsed.damageDice||null,damageType:parsed.damageType||null,saveAbility:parsed.saveAbility||null,requiresConcentration:parsed.requiresConcentration,origin:JutsuOrigin.DM_CUSTOM,pool:"ELEMENTAL",natures:{create:natureIds.map(chakraNatureId=>({chakraNatureId}))},prerequisites:{create:prerequisiteIds.map(prerequisiteJutsuId=>({prerequisiteJutsuId}))}}});revalidatePath(`/campaign/${campaignId}/jutsu-library`);return j.id;}
export async function updateCustomJutsu(campaignId:string,jutsuId:string,fd:FormData){await requireCampaign(campaignId,true);const current=await prisma.jutsu.findFirst({where:{id:jutsuId,campaignId,origin:JutsuOrigin.DM_CUSTOM}});if(!current)throw new Error("Custom-Jutsu nicht gefunden");const {parsed,natureIds,prerequisiteIds}=await customData(campaignId,fd);await prisma.$transaction(async tx=>{await tx.jutsuChakraNature.deleteMany({where:{jutsuId}});await tx.jutsuPrerequisite.deleteMany({where:{jutsuId}});await tx.jutsu.update({where:{id:jutsuId},data:{name:parsed.name,japaneseName:parsed.japaneseName||null,description:parsed.description,rank:parsed.rank,chakraCost:parsed.chakraCost,range:parsed.range||"Self",duration:parsed.duration||"Instantaneous",actionType:parsed.actionType||"Action",attackType:parsed.attackType||null,damageDice:parsed.damageDice||null,damageType:parsed.damageType||null,saveAbility:parsed.saveAbility||null,requiresConcentration:parsed.requiresConcentration,natures:{create:natureIds.map(chakraNatureId=>({chakraNatureId}))},prerequisites:{create:prerequisiteIds.map(prerequisiteJutsuId=>({prerequisiteJutsuId}))}}})});revalidatePath(`/campaign/${campaignId}/jutsu-library`);}
export async function deleteCustomJutsu(campaignId:string,jutsuId:string){await requireCampaign(campaignId,true);const current=await prisma.jutsu.findFirst({where:{id:jutsuId,campaignId,origin:JutsuOrigin.DM_CUSTOM}});if(!current)throw new Error("Custom-Jutsu nicht gefunden");await prisma.$transaction([prisma.characterJutsu.deleteMany({where:{jutsuId}}),prisma.jutsuPrerequisite.deleteMany({where:{OR:[{jutsuId},{prerequisiteJutsuId:jutsuId}]}}),prisma.jutsuChakraNature.deleteMany({where:{jutsuId}}),prisma.jutsu.delete({where:{id:jutsuId}})]);revalidatePath(`/campaign/${campaignId}/jutsu-library`);}
export async function setJutsuLibraryAccess(campaignId: string, value: JutsuLibraryAccess) { await requireCampaign(campaignId, true); await prisma.campaign.update({ where: { id: campaignId }, data: { jutsuLibraryAccess: value } }); revalidatePath(`/campaign/${campaignId}`); }
export async function createGameSession(campaignId: string, fd: FormData) { await requireCampaign(campaignId, true); const count = await prisma.gameSession.count({ where: { campaignId } }); await prisma.gameSession.create({ data: { campaignId, number: count + 1, title: text(fd, "title") || `Session ${count + 1}`, summary: text(fd, "summary"), playerNotes: text(fd, "playerNotes"), dmNotes: text(fd, "dmNotes") } }); revalidatePath(`/campaign/${campaignId}/sessions`); }
export async function updateGameSession(campaignId: string, sessionId: string, fd: FormData) { await requireCampaign(campaignId, true); await prisma.gameSession.updateMany({ where: { id: sessionId, campaignId }, data: { title: text(fd, "title"), summary: text(fd, "summary"), playerNotes: text(fd, "playerNotes"), dmNotes: text(fd, "dmNotes"), status: text(fd, "status") as GameSessionStatus } }); revalidatePath(`/campaign/${campaignId}/sessions/${sessionId}`); }
export async function createLocation(campaignId: string, fd: FormData) { await requireCampaign(campaignId, true); await prisma.location.create({ data: { campaignId, slug: text(fd, "slug"), name: text(fd, "name"), type: text(fd, "type") as LocationType, shortDescription: text(fd, "shortDescription"), description: text(fd, "description"), playerVisible: fd.get("playerVisible") === "on", parentId: text(fd, "parentId") || null } }); revalidatePath(`/campaign/${campaignId}/world`); }
export async function updateLocation(campaignId: string, locationId: string, fd: FormData) { await requireCampaign(campaignId, true); await prisma.location.updateMany({ where: { id: locationId, campaignId }, data: { name: text(fd, "name"), description: text(fd, "description"), shortDescription: text(fd, "shortDescription"), playerVisible: fd.get("playerVisible") === "on", type: text(fd, "type") as LocationType } }); revalidatePath(`/campaign/${campaignId}/world`); }
