"use server";
import { Reservoir, RegenRank } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { calculateMaxChakra, clamp, getLimitBreakHpCost, longRestState, preserveChakra, shortRestState } from "@/lib/rules";
import { requireCampaign } from "@/lib/session";
const getCharacter=async(campaignId:string,characterId:string)=>{await requireCampaign(campaignId,true);const c=await prisma.character.findFirst({where:{id:characterId,campaignId}});if(!c)throw new Error("Character not found");return c};
const redirectBack=(campaignId:string,characterId:string)=>{void campaignId;void characterId;};
export async function toggleSavingThrow(campaignId:string,characterId:string,ability:string){await getCharacter(campaignId,characterId);const key={characterId_ability:{characterId,ability}};const existing=await prisma.savingThrowProficiency.findUnique({where:key});if(existing)await prisma.savingThrowProficiency.delete({where:key});else await prisma.savingThrowProficiency.create({data:{characterId,ability}});}
export async function setSkillProficiency(campaignId:string,characterId:string,skill:string,proficiency:"NONE"|"PROFICIENT"|"EXPERTISE"){await getCharacter(campaignId,characterId);await prisma.skillProficiencyRecord.upsert({where:{characterId_skill:{characterId,skill}},create:{characterId,skill,proficiency},update:{proficiency}});}
export async function updateCharacter(campaignId:string,characterId:string,fd:FormData){const old=await getCharacter(campaignId,characterId);const level=clamp(Number(fd.get("level")),1,20);const con=Number(fd.get("con")),wis=Number(fd.get("wis"));const reservoir=String(fd.get("reservoir")) as Reservoir;const maxChakra=calculateMaxChakra(level,con,wis,reservoir,Number(fd.get("customReservoirMultiplier")||1));const oldMax=calculateMaxChakra(old.level,old.con,old.wis,old.reservoir,old.customReservoirMultiplier??1);const maxHp=Math.max(1,Number(fd.get("maxHp")));const requestedChakra=fd.get("currentChakra");await prisma.character.update({where:{id:old.id},data:{name:String(fd.get("name")),level,background:String(fd.get("background")||""),alignment:String(fd.get("alignment")||""),description:String(fd.get("description")||""),speed:Math.max(0,Number(fd.get("speed"))),maxHp,currentHp:clamp(Number(fd.get("currentHp")),0,maxHp),acOverride:fd.get("acOverride")?Number(fd.get("acOverride")):null,str:Number(fd.get("str")),dex:Number(fd.get("dex")),con,int:Number(fd.get("int")),wis,cha:Number(fd.get("cha")),reservoir,customReservoirMultiplier:reservoir==="SPECIAL"?Number(fd.get("customReservoirMultiplier")):null,regenRank:String(fd.get("regenRank")) as RegenRank,controlRank:String(fd.get("controlRank")) as RegenRank,currentChakra:requestedChakra===null?preserveChakra(old.currentChakra,oldMax,maxChakra):clamp(Number(requestedChakra),0,maxChakra),breakthroughPoints:Math.max(0,Number(fd.get("breakthroughPoints")))}});redirectBack(campaignId,characterId);}
export async function adjustHp(campaignId:string,characterId:string,mode:"damage"|"heal",amount:number){const c=await getCharacter(campaignId,characterId);const next=mode==="damage"?clamp(c.currentHp-amount,0,c.maxHp):clamp(c.currentHp+amount,0,c.maxHp);await prisma.character.update({where:{id:c.id},data:{currentHp:next,...(mode==="heal"&&c.currentHp===0&&next>0?{deathSaveSuccesses:0,deathSaveFailures:0,severelyWounded:true}:{})}});}
export async function adjustChakra(campaignId:string,characterId:string,mode:"spend"|"restore",amount:number){const c=await getCharacter(campaignId,characterId);const max=calculateMaxChakra(c.level,c.con,c.wis,c.reservoir,c.customReservoirMultiplier??1);await prisma.character.update({where:{id:c.id},data:{currentChakra:clamp(mode==="spend"?c.currentChakra-amount:c.currentChakra+amount,0,max)}});}
export async function performShortRest(campaignId:string,characterId:string){const c=await getCharacter(campaignId,characterId);const max=calculateMaxChakra(c.level,c.con,c.wis,c.reservoir,c.customReservoirMultiplier??1);const next=shortRestState(c.currentHp,c.maxHp,c.currentChakra,max,c.regenRank,c.shortRestsSinceLongRest);await prisma.character.update({where:{id:c.id},data:next});}
export async function performLongRest(campaignId:string,characterId:string){const c=await getCharacter(campaignId,characterId);const max=calculateMaxChakra(c.level,c.con,c.wis,c.reservoir,c.customReservoirMultiplier??1);await prisma.character.update({where:{id:c.id},data:longRestState(c.maxHp,max)});}
export async function updateDeathSave(campaignId:string,characterId:string,field:"success"|"failure"|"reset"){const c=await getCharacter(campaignId,characterId);const data=field==="reset"?{deathSaveSuccesses:0,deathSaveFailures:0}:{[field==="success"?"deathSaveSuccesses":"deathSaveFailures"]:{increment:1}};const key=field==="success"?"deathSaveSuccesses":"deathSaveFailures";if(field!=="reset"&&c[key]>=3)throw new Error("Death save limit reached");await prisma.character.update({where:{id:c.id},data});}
export async function toggleNature(campaignId:string,characterId:string,natureId:string,mode:"add"|"remove"|"primary"){await getCharacter(campaignId,characterId);const links=await prisma.characterChakraNature.findMany({where:{characterId}});if(mode==="add")await prisma.characterChakraNature.create({data:{characterId,chakraNatureId:natureId,source:"DM_GRANTED"}});if(mode==="remove"){const link=links.find(x=>x.chakraNatureId===natureId);if(!link||link.isPrimary)throw new Error("Cannot remove the primary nature");await prisma.characterChakraNature.delete({where:{characterId_chakraNatureId:{characterId,chakraNatureId:natureId}}});}if(mode==="primary")await prisma.$transaction([prisma.characterChakraNature.updateMany({where:{characterId},data:{isPrimary:false}}),prisma.characterChakraNature.update({where:{characterId_chakraNatureId:{characterId,chakraNatureId:natureId}},data:{isPrimary:true}})]);}
export async function toggleJutsu(campaignId:string,characterId:string,jutsuId:string,mode:"add"|"remove"){await getCharacter(campaignId,characterId);if(mode==="add")await prisma.characterJutsu.create({data:{characterId,jutsuId,source:"DM_GRANTED"}});else await prisma.characterJutsu.delete({where:{characterId_jutsuId:{characterId,jutsuId}}});}
export async function updateDmData(campaignId:string,characterId:string,fd:FormData){await getCharacter(campaignId,characterId);await prisma.characterDMData.upsert({where:{characterId},create:{characterId,notes:String(fd.get("notes")||""),secretInformation:String(fd.get("secretInformation")||"")},update:{notes:String(fd.get("notes")||""),secretInformation:String(fd.get("secretInformation")||"")}});}
export async function performLimitBreak(campaignId:string,characterId:string,jutsuId:string){const c=await getCharacter(campaignId,characterId);if(c.limitBreakUsed||c.currentChakra!==0)throw new Error("Limit Break unavailable");const j=await prisma.jutsu.findUniqueOrThrow({where:{id:jutsuId}});await prisma.character.update({where:{id:c.id},data:{currentHp:clamp(c.currentHp-getLimitBreakHpCost(j.rank),0,c.maxHp),limitBreakUsed:true}});}

