import type { JutsuSeedRecord } from "./jutsu-seed-types.generated";

export const CharacterSignaturesJutsu = [
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "chakra-skalpell",
    "name": "Chakra-Skalpell",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Medizinisches Ninjutsu / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Bonus Action",
    "range": null,
    "duration": "1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Chakra-Skalpell\n\n**Typ:** Medizinisches Ninjutsu / Offensive  \n**Rang:** B  \n**Bonus Action**  \n**Chakra:** 20  \n**Dauer:** 1 Minute\n\nAyame formt hochpräzise Chakra-Klingen um ihre Hände.\n\nIhre unbewaffneten Angriffe verursachen währenddessen:\n\n**3d6 Chakra/Slashing Damage**\n\nstatt des normalen Schadens.\n\nBei einem Critical Hit kann Ayame statt zusätzlichen Schadens die Muskulatur des Ziels stören.\n\nDas Ziel muss einen:\n\n**CON Save DC 19**\n\nbestehen.\n\nBei Fehlschlag wird seine Movement Speed bis zum Ende seines nächsten Zuges halbiert.\n\nAyame entwickelte diese Technik ursprünglich für medizinische Anwendungen.\n\nSie kann damit kämpfen.\n\n**Sie möchte es nur normalerweise nicht.**\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "saikan-chushutsu-no-jutsu-giftentfernung",
    "name": "Saikan Chūshutsu no Jutsu – Giftentfernung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Medizinisches Ninjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 25,
    "chakraText": "25",
    "actionType": "Action",
    "range": "Berührung",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Saikan Chūshutsu no Jutsu – Giftentfernung\n\n**Typ:** Medizinisches Ninjutsu  \n**Rang:** B  \n**Action**  \n**Chakra:** 25  \n**Reichweite:** Berührung\n\nAyame entfernt oder neutralisiert ein Gift aus dem Körper eines Patienten.\n\nBei gewöhnlichen Giften endet **Poisoned** unmittelbar.\n\nBei außergewöhnlichen oder unbekannten Giften erhält das Ziel Advantage auf seinen nächsten Save, während Ayame Informationen über die Zusammensetzung erhält.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "suiton-seijosui-reinigendes-wasser",
    "name": "Suiton: Seijōsui – Reinigendes Wasser",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Suiton / Medizin & Utility",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 10,
    "chakraText": "10",
    "actionType": "Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WATER"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Suiton: Seijōsui – Reinigendes Wasser\n\n**Typ:** Suiton / Medizin & Utility  \n**Rang:** C  \n**Action**  \n**Chakra:** 10\n\nAyame erzeugt und kontrolliert eine kleine Menge besonders sauberen Wassers.\n\nEs kann verwendet werden zur:\n\n- Wundreinigung\n- Instrumentenreinigung\n- Kühlung\n- Entfernung oberflächlicher Verunreinigungen\n- medizinischen Vorbereitung\n\nIm Kampf kann Ayame es außerdem verwenden, um kleinere Mengen gefährlicher Flüssigkeit von einem Ziel oder Gegenstand zu entfernen.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "suiton-suimaku-wasserschleier",
    "name": "Suiton: Suimaku – Wasserschleier",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Suiton / Defensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 15,
    "chakraText": "15",
    "actionType": "Reaction",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WATER"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Suiton: Suimaku – Wasserschleier\n\n**Typ:** Suiton / Defensive  \n**Rang:** C  \n**Reaction**  \n**Chakra:** 15\n\nAyame erzeugt unmittelbar eine kompakte Wasserbarriere.\n\nSie reduziert eintreffenden Schaden um:\n\n**3d8 + 5**\n\nDie Technik ist wesentlich kleiner als Raizens Wasserformationswand und primär zur Selbstverteidigung oder zum Schutz eines Patienten gedacht.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "chakra-stabilisierung",
    "name": "Chakra-Stabilisierung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Medizinisches Ninjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Action",
    "range": "Berührung",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Chakra-Stabilisierung\n\n**Typ:** Medizinisches Ninjutsu  \n**Rang:** B  \n**Action**  \n**Chakra:** 20  \n**Reichweite:** Berührung\n\nAyame stabilisiert den Chakrafluss eines Ziels.\n\nDas Ziel kann unmittelbar einen Saving Throw gegen einen Effekt wiederholen, der seinen Chakrafluss beeinträchtigt.\n\nZusätzlich erhält es bis zum Ende seines nächsten Zuges:\n\n**Advantage auf CON Saves.**\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "notfallstabilisierung",
    "name": "Notfallstabilisierung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Medizinisches Ninjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 40,
    "chakraText": "40",
    "actionType": "Action",
    "range": "Berührung",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Notfallstabilisierung\n\n**Typ:** Medizinisches Ninjutsu  \n**Rang:** A  \n**Action**  \n**Chakra:** 40  \n**Reichweite:** Berührung\n\nDiese Technik dient nicht primär dazu, einen Patienten vollständig zu heilen.\n\nSie dient dazu, **ihn am Leben zu halten.**\n\nEin Ziel mit 0 HP erhält sofort:\n\n**25 HP**\n\nund wird stabilisiert.\n\nBefindet sich sein Chakra ebenfalls auf 0, erhält es zusätzlich:\n\n**10 Chakra**.\n\nDasselbe Ziel kann von dieser Technik nur **einmal pro Long Rest** profitieren.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ayame",
    "slug": "pfad-des-lebens",
    "name": "Pfad des Lebens",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": "Medizinisches Ninjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 80,
    "chakraText": "80",
    "actionType": "Action",
    "range": "Berührung",
    "duration": "Konzentration, maximal 3 Runden",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "## Pfad des Lebens\n\n**Typ:** Medizinisches Ninjutsu  \n**Rang:** S  \n**Action**  \n**Chakra:** **80**  \n**Reichweite:** Berührung  \n**Dauer:** Konzentration, maximal 3 Runden\n\nAyame verbindet ihren Chakrafluss unmittelbar mit dem Chakra-Netzwerk eines schwer verletzten Patienten.\n\nBeim Aktivieren erhält das Ziel:\n\n**6d10 + 20 HP**\n\nSolange Ayame die Verbindung aufrechterhält, regeneriert das Ziel zu Beginn jedes seiner Züge:\n\n**3d10 HP**\n\nund besitzt Advantage auf Death-, Constitution- und körperliche Status-Saves.\n\nAyame kann sich währenddessen bewegen, muss jedoch Körperkontakt halten und kann keine anderen Jutsu verwenden.\n\nErleidet Ayame Schaden, muss sie einen **CON Save** ablegen, um die Verbindung aufrechtzuerhalten.\n\n**Pfad des Lebens kann keine tote Kreatur wiederbeleben.**\n\nDie Technik kauft Zeit.\n\nManchmal sind genau diese Sekunden der Unterschied zwischen Leben und Tod.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Kaito",
    "slug": "raiton-raiko-no-yaiba-klinge-des-blitzes",
    "name": "Raiton: Raikō no Yaiba – Klinge des Blitzes",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Raiton / Kenjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Bonus Action",
    "range": null,
    "duration": "bis 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "## Raiton: Raikō no Yaiba – Klinge des Blitzes\n\n**Typ:** Raiton / Kenjutsu  \n**Rang:** B  \n**Bonus Action**  \n**Chakra:** 20  \n**Dauer:** bis 1 Minute\n\nKaito umhüllt sein Katana mit konzentriertem Raiton-Chakra.\n\nSeine Katana-Angriffe verursachen zusätzlich:\n\n**1d8 Lightning Damage**\n\nGegen nichtmagische beziehungsweise nicht durch Chakra verstärkte Rüstung erhält Kaito **+1 auf Attack Rolls**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Kaito",
    "slug": "raiton-shunpu-blitzschritt",
    "name": "Raiton: Shunpū – Blitzschritt",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Raiton / Mobilität",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Bonus Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Raiton: Shunpū – Blitzschritt\n\n**Typ:** Raiton / Mobilität  \n**Rang:** B  \n**Bonus Action**  \n**Chakra:** 20\n\nKaito verstärkt für einen Augenblick seine Muskulatur mit Raiton.\n\nEr bewegt sich bis zu **30 ft**, ohne Opportunity Attacks auszulösen.\n\nDieser Effekt zählt nicht gegen seine normale Movement-Geschwindigkeit.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Kaito",
    "slug": "suiton-suiben-wasserpeitsche",
    "name": "Suiton: Suiben – Wasserpeitsche",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Suiton / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Action",
    "range": "30 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WATER"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Suiton: Suiben – Wasserpeitsche\n\n**Typ:** Suiton / Kontrolle  \n**Rang:** C  \n**Action**  \n**Chakra:** 20  \n**Reichweite:** 30 ft\n\nKaito formt Wasser zu einer kompakten Peitsche.\n\n**Melee Ninjutsu Attack:** +11\n\n**Treffer:** `3d8` Wasserschaden.\n\nAnschließend kann Kaito das Ziel bis zu **15 ft zu sich ziehen**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Kaito",
    "slug": "raiton-ikazuchi-no-kusari-blitzfessel",
    "name": "Raiton: Ikazuchi no Kusari – Blitzfessel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Raiton / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 45,
    "chakraText": "45",
    "actionType": "Action",
    "range": "40 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Raiton: Ikazuchi no Kusari – Blitzfessel\n\n**Typ:** Raiton / Kontrolle  \n**Rang:** A  \n**Action**  \n**Chakra:** 45  \n**Reichweite:** 40 ft\n\nKaito leitet Raiton durch eine vorhandene Wasserquelle oder eine zuvor eingesetzte Suiton-Technik.\n\nAlle Kreaturen innerhalb eines **15-ft-Bereichs** um den Zielpunkt führen einen:\n\n**CON Save DC 19**\n\ndurch.\n\nBei Fehlschlag:\n\n**6d8 Lightning Damage**\n\nund die Kreatur ist bis zum Ende ihres nächsten Zuges **Restrained**.\n\nBei Erfolg:\n\nHalber Schaden und kein Restrained.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Kaito",
    "slug": "raiton-kurogawa-ryu-donnernder-fang",
    "name": "Raiton: Kurogawa-ryū – Donnernder Fang",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Raiton / Kenjutsu",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 50,
    "chakraText": "50",
    "actionType": "Action",
    "range": "Movement + 5 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Raiton: Kurogawa-ryū – Donnernder Fang\n\n**Typ:** Raiton / Kenjutsu  \n**Rang:** A  \n**Action**  \n**Chakra:** 50  \n**Reichweite:** Movement + 5 ft\n\nKaito fokussiert Raiton in seinen Körper und seine Klinge und stürmt auf ein einzelnes Ziel zu.\n\nEr darf sich bis zu seiner Movement-Geschwindigkeit bewegen, ohne Opportunity Attacks auszulösen.\n\nAnschließend:\n\n**Melee Weapon Attack:** +11\n\nBei Treffer:\n\n**2d10 + 5 Slashing**\n\n- **6d8 Lightning**\n\nDas Ziel muss anschließend einen:\n\n**CON Save DC 19**\n\nbestehen.\n\nBei Fehlschlag ist seine Movement Speed bis zum Ende seines nächsten Zuges **0**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "futon-kaze-no-yaiba-windklinge",
    "name": "Fūton: Kaze no Yaiba – Windklinge",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Fūton / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 15,
    "chakraText": "15",
    "actionType": "Action",
    "range": "60 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WIND"
    ],
    "requiredNatures": [],
    "rawMarkdown": "## Fūton: Kaze no Yaiba – Windklinge\n\n**Typ:** Fūton / Offensive  \n**Rang:** C  \n**Action**  \n**Chakra:** 15  \n**Reichweite:** 60 ft\n\nRen erzeugt eine dünne, komprimierte Windklinge.\n\n**Ranged Ninjutsu Attack:** +11\n\n**Treffer:** `4d8 Slashing Damage`\n\nDie Technik ist nahezu unsichtbar und entsprechend schwierig einzuschätzen.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "futon-kaze-no-michi-pfad-des-windes",
    "name": "Fūton: Kaze no Michi – Pfad des Windes",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Fūton / Utility & Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 25,
    "chakraText": "25",
    "actionType": "Bonus Action",
    "range": "60 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WIND"
    ],
    "requiredNatures": [],
    "rawMarkdown": "## Fūton: Kaze no Michi – Pfad des Windes\n\n**Typ:** Fūton / Utility & Kontrolle  \n**Rang:** B  \n**Bonus Action**  \n**Chakra:** 25  \n**Reichweite:** 60 ft\n\nRen verändert für einen Augenblick Luftströmungen innerhalb eines Bereichs.\n\nBis zum Beginn seines nächsten Zuges kann er einem sichtbaren Fernkampfangriff innerhalb des Bereichs entweder:\n\n**+2 auf den Attack Roll**\n\noder\n\n**−2 auf den Attack Roll**\n\ngeben.\n\nRen entscheidet, nachdem der Angriff angekündigt wurde, aber bevor gewürfelt wird.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "doton-erde-der-fesselung",
    "name": "Doton: Erde der Fesselung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Doton / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 30,
    "chakraText": "30",
    "actionType": "Action",
    "range": "60 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "EARTH"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Doton: Erde der Fesselung\n\n**Typ:** Doton / Kontrolle  \n**Rang:** B  \n**Action**  \n**Chakra:** 30  \n**Reichweite:** 60 ft  \n**Bereich:** 15-ft-Radius\n\nRen destabilisiert und verdichtet den Boden um seine Gegner.\n\nKreaturen im Bereich führen einen:\n\n**DEX Save DC 19**\n\ndurch.\n\nBei Fehlschlag:\n\n**Restrained**\n\nbis zum Ende ihres nächsten Zuges.\n\nDer Bereich gilt anschließend für eine Minute als **Difficult Terrain**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "genjutsu-falscher-schritt",
    "name": "Genjutsu: Falscher Schritt",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Genjutsu / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Reaction",
    "range": "30 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Genjutsu: Falscher Schritt\n\n**Typ:** Genjutsu / Kontrolle  \n**Rang:** C  \n**Reaction**  \n**Chakra:** 20  \n**Reichweite:** 30 ft\n\nRen manipuliert für einen Augenblick die räumliche Wahrnehmung eines Gegners.\n\nWenn eine Kreatur innerhalb der Reichweite einen Angriff gegen Ren durchführt, muss sie einen:\n\n**WIS Save DC 19**\n\nbestehen.\n\nBei Fehlschlag erhält der Angriff **Disadvantage**.\n\nScheitern beide Attack Rolls am AC, darf Ren sich unmittelbar **10 ft bewegen**, ohne Opportunity Attacks auszulösen.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "genjutsu-kai-illusionsbrechung",
    "name": "Genjutsu Kai – Illusionsbrechung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Genjutsu / Support",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 15,
    "chakraText": "15",
    "actionType": null,
    "range": "Selbst / Berührung",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Genjutsu Kai – Illusionsbrechung\n\n**Typ:** Genjutsu / Support  \n**Rang:** C  \n**Action oder Reaction**  \n**Chakra:** 15  \n**Reichweite:** Selbst / Berührung\n\nRen stört gezielt den Chakrafluss.\n\nEr oder eine berührte Kreatur darf einen Saving Throw gegen einen bestehenden Genjutsu-Effekt mit **Advantage wiederholen**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "futon-shinkusen-vakuumlinie",
    "name": "Fūton: Shinkūsen – Vakuumlinie",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Fūton / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 45,
    "chakraText": "45",
    "actionType": "Action",
    "range": "90-ft-Linie, 5 ft breit",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WIND"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Fūton: Shinkūsen – Vakuumlinie\n\n**Typ:** Fūton / Offensive  \n**Rang:** A  \n**Action**  \n**Chakra:** 45  \n**Reichweite:** 90-ft-Linie, 5 ft breit\n\nRen verdichtet Windchakra zu einer extrem schmalen Schneidlinie.\n\nKreaturen innerhalb der Linie führen einen:\n\n**DEX Save DC 19**\n\ndurch.\n\nFehlschlag:\n\n**8d8 Slashing Damage**\n\nErfolg:\n\nHalber Schaden.\n\nDie Technik ignoriert einfache nicht-chakraverstärkte Deckung.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "futon-senpu-kekkai-wirbelbarriere",
    "name": "Fūton: Senpū Kekkai – Wirbelbarriere",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Fūton / Defensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 45,
    "chakraText": "45",
    "actionType": "Action",
    "range": null,
    "duration": "bis zum Beginn seines nächsten Zuges",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WIND"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Fūton: Senpū Kekkai – Wirbelbarriere\n\n**Typ:** Fūton / Defensive  \n**Rang:** A  \n**Action**  \n**Chakra:** 45  \n**Bereich:** 15-ft-Radius um Ren  \n**Dauer:** bis zum Beginn seines nächsten Zuges\n\nEin rotierender Windstrom entsteht um Ren.\n\nVerbündete innerhalb des Bereichs erhalten:\n\n**+2 AC gegen Fernkampfangriffe**\n\nund Advantage auf STR Saves gegen Effekte, die sie verschieben würden.\n\nNicht verstärkte kleine Projektile werden automatisch abgelenkt.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Ren",
    "slug": "kafig-des-windes",
    "name": "Käfig des Windes",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": "Fūton / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 80,
    "chakraText": "80",
    "actionType": "Action",
    "range": "60 ft",
    "duration": "Konzentration, maximal 3 Runden",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "## Käfig des Windes\n\n**Typ:** Fūton / Kontrolle  \n**Rang:** S  \n**Action**  \n**Chakra:** 80  \n**Reichweite:** 60 ft  \n**Bereich:** 20-ft-Radius  \n**Dauer:** Konzentration, maximal 3 Runden\n\nRen erzeugt mehrere rotierende Schichten aus hochverdichtetem Windchakra um einen Bereich.\n\nKreaturen innerhalb des Käfigs können sich bewegen.\n\nVersuchen sie jedoch, den Bereich zu verlassen, müssen sie einen:\n\n**DEX Save DC 19**\n\ndurchführen.\n\nBei Fehlschlag:\n\n**6d10 Slashing Damage**\n\nund die Bewegung wird gestoppt.\n\nBei Erfolg:\n\nHalber Schaden und die Kreatur kann den Käfig verlassen.\n\nFernkampfangriffe durch die Wand des Käfigs werden mit **Disadvantage** durchgeführt.\n\nDer Käfig dient Ren nicht primär dazu, jemanden zu töten.\n\nEr dient dazu, einen Gegner **dort zu halten, wo Ren ihn haben möchte.**\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "raiton-raikyu-blitzkugel",
    "name": "Raiton: Raikyū – Blitzkugel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Raiton / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Action",
    "range": "90 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Raiton: Raikyū – Blitzkugel\n\n**Typ:** Raiton / Offensive  \n**Rang:** C  \n**Action**  \n**Chakra:** 20  \n**Reichweite:** 90 ft\n\n**Ranged Ninjutsu Attack:** +12\n\nTreffer:\n\n**5d8 Lightning Damage**\n\nDas Ziel verliert bis zum Beginn seines nächsten Zuges seine Reaction.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "raiton-denki-shunpo-elektrischer-schritt",
    "name": "Raiton: Denki Shunpō – Elektrischer Schritt",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Raiton / Mobilität",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Bonus Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "LIGHTNING"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Raiton: Denki Shunpō – Elektrischer Schritt\n\n**Typ:** Raiton / Mobilität  \n**Rang:** B  \n**Bonus Action**  \n**Chakra:** 20\n\nRenji verstärkt kurzfristig sein Nervensystem und seine Muskulatur.\n\nEr bewegt sich bis zu **30 ft**, ohne Opportunity Attacks auszulösen.\n\nPrimär verwendet Renji diese Technik nicht, um Gegner zu verfolgen.\n\nEr benutzt sie, um **wieder Abstand herzustellen**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "nikkoton-solarflamme",
    "name": "Nikkōton: Solarflamme",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Nikkōton / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 35,
    "chakraText": "35",
    "actionType": "Action",
    "range": "90 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "NIKKOTON"
    ],
    "requiredNatures": [
      "FIRE",
      "LIGHTNING"
    ],
    "rawMarkdown": "# Nikkōton: Solarflamme\n\n**Typ:** Nikkōton / Offensive  \n**Rang:** B  \n**Action**  \n**Chakra:** 35  \n**Reichweite:** 90 ft\n\nRenji schleudert eine weiß-goldene Flamme aus Nikkōton.\n\n**Ranged Ninjutsu Attack:** +12\n\nTreffer:\n\n**4d8 Fire + 4d8 Radiant Damage**\n\nRenji kann eine Eigenschaft wählen:\n\n**Hitze:** Das Ziel erleidet zu Beginn seines nächsten Zuges zusätzlich `2d8 Fire Damage`.\n\n**Licht:** CON Save DC 20 oder **Blinded** bis zum Ende des nächsten Zuges.\n\n**Entladung:** Das Ziel wird 15 ft zurückgestoßen und verliert seine Reaction.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "nikkoton-solareruption",
    "name": "Nikkōton: Solareruption",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Nikkōton / AoE",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 65,
    "chakraText": "65",
    "actionType": "Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "NIKKOTON"
    ],
    "requiredNatures": [
      "FIRE",
      "LIGHTNING"
    ],
    "rawMarkdown": "# Nikkōton: Solareruption\n\n**Typ:** Nikkōton / AoE  \n**Rang:** A  \n**Action**  \n**Chakra:** 65  \n**Bereich:** 30-ft-Kegel\n\nRenji setzt explosionsartig weiß-goldenes Chakra frei.\n\n**DEX Save DC 20**\n\nFehlschlag:\n\n**5d8 Fire + 5d8 Radiant Damage**\n\nErfolg:\n\nHalber Schaden.\n\nKreaturen, die den Save nicht bestehen, müssen zusätzlich einen:\n\n**CON Save DC 20**\n\nbestehen oder sind bis zum Ende ihres nächsten Zuges **Blinded**.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "nikkoton-sonnenstrahl",
    "name": "Nikkōton: Sonnenstrahl",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Nikkōton / Präzisionsangriff",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 60,
    "chakraText": "60",
    "actionType": "Action",
    "range": "**150 ft**",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "NIKKOTON"
    ],
    "requiredNatures": [
      "FIRE",
      "LIGHTNING"
    ],
    "rawMarkdown": "# Nikkōton: Sonnenstrahl\n\n**Typ:** Nikkōton / Präzisionsangriff  \n**Rang:** A  \n**Action**  \n**Chakra:** 60  \n**Reichweite:** **150 ft**\n\nRenji komprimiert Nikkōton auf einen extrem kleinen Punkt und setzt es als weiß-goldenen Energiestrahl frei.\n\n**Ranged Ninjutsu Attack:** +12\n\nTreffer:\n\n**6d10 Radiant + 3d10 Fire Damage**\n\nDer Angriff ignoriert **Half Cover**.\n\nDie Technik besitzt praktisch keine Flächenwirkung.\n\nGenau deshalb entwickelte Renji sie.\n\n**Maximale Energie. Minimale Kollateralschäden.**\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "nikkoton-korona",
    "name": "Nikkōton: Korona",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Nikkōton / Defensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 50,
    "chakraText": "50",
    "actionType": "Bonus Action",
    "range": null,
    "duration": "Konzentration, maximal 3 Runden",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "NIKKOTON"
    ],
    "requiredNatures": [
      "FIRE",
      "LIGHTNING"
    ],
    "rawMarkdown": "# Nikkōton: Korona\n\n**Typ:** Nikkōton / Defensive  \n**Rang:** A  \n**Bonus Action**  \n**Chakra:** 50  \n**Dauer:** Konzentration, maximal 3 Runden\n\nRenji umgibt seinen Körper mit einer weiß-goldenen Schicht aus Nikkōton.\n\nEr erhält:\n\n**+2 AC**\n\nund Resistance gegen:\n\n**Fire und Lightning Damage**\n\nEine Kreatur, die Renji im Nahkampf trifft, erleidet:\n\n**2d8 Radiant Damage**.\n\nDie Technik ist gleichzeitig einer seiner wichtigsten Konter gegen aggressive Nahkämpfer.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "nikkoton-sonnenkern",
    "name": "Nikkōton: Sonnenkern",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": "Nikkōton / Vorbereitung",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 80,
    "chakraText": "80",
    "actionType": "Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "NIKKOTON"
    ],
    "requiredNatures": [
      "FIRE",
      "LIGHTNING"
    ],
    "rawMarkdown": "# Nikkōton: Sonnenkern\n\n**Typ:** Nikkōton / Vorbereitung  \n**Rang:** S  \n**Action**  \n**Chakra:** 80\n\nRenji erzeugt eine kleine, extrem verdichtete Kugel aus Nikkōton-Chakra.\n\nDer Sonnenkern schwebt in seiner unmittelbaren Nähe.\n\nEr kann maximal **einen Sonnenkern gleichzeitig** kontrollieren.\n\nDer Kern bleibt für maximal drei Runden bestehen.\n\nWährend dieser Zeit kann Renji ihn für andere Nikkōton-Techniken verwenden.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Renji",
    "slug": "weie-sonne",
    "name": "Weiße Sonne",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": "Nikkōton / Ultimate AoE",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 130,
    "chakraText": "130",
    "actionType": "Action",
    "range": "120 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "## Weiße Sonne\n\n**Typ:** Nikkōton / Ultimate AoE  \n**Rang:** S  \n**Action**  \n**Chakra:** **130**  \n**Reichweite:** 120 ft  \n**Bereich:** 40-ft-Radius\n\nRenji komprimiert enorme Mengen Nikkōton und setzt sie anschließend explosionsartig frei.\n\nFür einen kurzen Moment entsteht eine weiß-goldene Lichtquelle, die so hell ist, dass die Umgebung beinahe farblos erscheint.\n\nAlle Kreaturen im Bereich führen einen:\n\n**DEX Save DC 20**\n\ndurch.\n\n### Fehlschlag\n\n**8d10 Radiant + 6d10 Fire Damage**\n\nund:\n\n**Blinded** bis zum Ende ihres nächsten Zuges.\n\n### Erfolg\n\nHalber Schaden und kein Blinded.\n\n---\n\n### Kollateralschaden\n\nBrennbare Materialien können entzündet werden.\n\nNicht verstärkte Strukturen können erheblich beschädigt werden.\n\n**Renji verwendet diese Technik deshalb niemals leichtfertig.**\n\nUnd insbesondere nicht mitten in Shiogakure.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "suiton-suiryu-no-kusari-ketten-des-wasserdrachen",
    "name": "Suiton: Suiryū no Kusari – Ketten des Wasserdrachen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Suiton / Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 30,
    "chakraText": "30",
    "actionType": "1 Action",
    "range": "60 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WATER"
    ],
    "requiredNatures": [],
    "rawMarkdown": "## Suiton: Suiryū no Kusari – Ketten des Wasserdrachen\n\n**Typ:** Suiton / Kontrolle  \n**Rang:** B  \n**Action:** 1 Action  \n**Chakra:** 30  \n**Reichweite:** 60 ft\n\nWasser formt sich zu drachenartigen Ketten und versucht ein Ziel festzusetzen.\n\n**DEX Save DC 19**\n\nBei Fehlschlag:\n\n**4d8 Wasserschaden** und **Restrained**.\n\nDas Ziel kann am Ende seines Zuges den Save wiederholen.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "suiton-explodierende-wasser-kollisionswelle",
    "name": "Suiton: Explodierende Wasser-Kollisionswelle",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Suiton / Gebietskontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 60,
    "chakraText": "60",
    "actionType": "1 Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "WATER"
    ],
    "requiredNatures": [],
    "rawMarkdown": "## Suiton: Explodierende Wasser-Kollisionswelle\n\n**Typ:** Suiton / Gebietskontrolle  \n**Rang:** A  \n**Action:** 1 Action  \n**Chakra:** 60  \n**Bereich:** 80-ft-Radius\n\nRaizen setzt enorme Mengen Wasser frei und überflutet das unmittelbare Schlachtfeld.\n\nKreaturen im Wirkungsbereich:\n\n**STR Save DC 19**\n\nBei Fehlschlag:\n\n**6d8 Schaden**, 20 ft Verschiebung und **Prone**.\n\nBei Erfolg halber Schaden und keine Verschiebung.\n\nDas erzeugte Wasser bleibt bestehen und kann anschließend für Raizens Suiton-Techniken verwendet werden.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "regenbarriere",
    "name": "Regenbarriere",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": "Suiton / Sensorik",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 35,
    "chakraText": "35",
    "actionType": "1 Action",
    "range": null,
    "duration": "Konzentration",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "requiredNatures": [],
    "rawMarkdown": "# Regenbarriere\n\n**Typ:** Suiton / Sensorik  \n**Rang:** B  \n**Action:** 1 Action  \n**Chakra:** 35  \n**Bereich:** 100-ft-Radius  \n**Dauer:** Konzentration\n\nRaizen erzeugt beziehungsweise manipuliert feinen Regen und verbindet diesen mit seinem Chakra.\n\nSolange eine Kreatur den Regen innerhalb des Wirkungsbereichs berührt, kann Raizen ihre **ungefähre Position wahrnehmen**.\n\nDadurch kann er Gegner selbst innerhalb seines Verstecks im Nebel lokalisieren.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "doton-puls-der-erde",
    "name": "Doton: Puls der Erde",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": "Doton / Sensorik & Kontrolle",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 15,
    "chakraText": "15",
    "actionType": "Bonus Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "EARTH"
    ],
    "requiredNatures": [],
    "rawMarkdown": "# Doton: Puls der Erde\n\n**Typ:** Doton / Sensorik & Kontrolle  \n**Rang:** C  \n**Bonus Action**  \n**Chakra:** 15  \n**Bereich:** 60 ft\n\nRaizen sendet Chakra durch den Boden und nimmt Bewegungen und Erschütterungen wahr.\n\nBis zum Beginn seines nächsten Zuges kennt er die Position von Kreaturen innerhalb des Bereiches, sofern diese Kontakt zum Boden besitzen.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "eisenversteck-festung-des-schwarzen-eisens",
    "name": "Eisenversteck: Festung des schwarzen Eisens",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": "Eisenversteck / Defensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 70,
    "chakraText": "70",
    "actionType": "1 Action",
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "IRON_RELEASE"
    ],
    "requiredNatures": [
      "WATER",
      "EARTH",
      "FIRE"
    ],
    "rawMarkdown": "# Eisenversteck: Festung des schwarzen Eisens\n\n**Typ:** Eisenversteck / Defensive  \n**Rang:** A  \n**Action:** 1 Action  \n**Chakra:** 70\n\nRaizen formt eine massive Eisenstruktur aus dem Gelände.\n\nDie Festung kann als Schutz für ihn und mehrere Verbündete dienen.\n\n**AC 22**  \n**HP 100**\n\nDie Struktur bleibt bestehen, bis sie zerstört oder von Raizen aufgelöst wird.\n\n---"
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "CHARACTER_SIGNATURE",
    "characterOrigin": "Raizen",
    "slug": "eisenversteck-schwarzer-eisenregen",
    "name": "Eisenversteck: Schwarzer Eisenregen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": "Eisenversteck / Offensive",
    "progressionType": "CHARACTER_SIGNATURE",
    "prerequisiteText": null,
    "chakraCost": 100,
    "chakraText": "100",
    "actionType": "1 Action",
    "range": "120 ft",
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [
      "IRON_RELEASE"
    ],
    "requiredNatures": [
      "WATER",
      "EARTH",
      "FIRE"
    ],
    "rawMarkdown": "# Eisenversteck: Schwarzer Eisenregen\n\n**Typ:** Eisenversteck / Offensive  \n**Rang:** S  \n**Action:** 1 Action  \n**Chakra:** 100  \n**Reichweite:** 120 ft  \n**Bereich:** 30-ft-Radius\n\nRaizen erzeugt zahlreiche verdichtete Eisenprojektile und lässt sie mit hoher Geschwindigkeit auf einen Bereich niedergehen.\n\n**DEX Save DC 19**\n\nFehlschlag:\n\n**10d10 Piercing Damage**\n\nErfolg:\n\nHalber Schaden.\n\nDas Gebiet wird anschließend durch Eisenfragmente zu **Difficult Terrain**.\n\n---"
  }
] satisfies JutsuSeedRecord[];
