import type { JutsuSeedRecord } from "./jutsu-seed-types.generated";

export const FoundationJutsu = [
  {
    "source": "CANON",
    "pool": "FOUNDATION",
    "slug": "water-walking-wasserlaufen",
    "name": "Water Walking / Wasserlaufen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Water Walking / Wasserlaufen**                          | Chakra an den Füßen laufend an die Wasseroberfläche anpassen        | Chakra-Control-Training                                                                                                                                                           |",
    "description": "Chakra an den Füßen laufend an die Wasseroberfläche anpassen",
    "role": "Chakra-Control-Training",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "genjutsu-release-illusionsauflosung",
    "name": "Genjutsu Release / Illusionsauflösung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Genjutsu Release / Illusionsauflösung**                 | Eigenen Chakrafluss stören, um ein erkanntes Genjutsu zu brechen    | frühes Anti-Genjutsu-Training                                                                                                                                                     |",
    "description": "Eigenen Chakrafluss stören, um ein erkanntes Genjutsu zu brechen",
    "role": "frühes Anti-Genjutsu-Training",
    "requiredNatures": []
  },
  {
    "source": "CANON",
    "pool": "FOUNDATION",
    "slug": "cloak-of-invisibility-tarnungs-technik",
    "name": "Cloak of Invisibility / Tarnungs-Technik",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Cloak of Invisibility / Tarnungs-Technik**              | Mit Umgebung/Tarnmaterial verschmelzen und sich verstecken          | Stealth-Mission ([Naruto Wiki](https://naruto.fandom.com/wiki/Cloak_of_Invisibility_Technique?utm_source=chatgpt.com \"Cloak of Invisibility Technique \\| Narutopedia \\| Fandom\")) |",
    "description": "Mit Umgebung/Tarnmaterial verschmelzen und sich verstecken",
    "role": "Stealth-Mission ([Naruto Wiki](https://naruto.fandom.com/wiki/Cloak_of_Invisibility_Technique?utm_source=chatgpt.com \"Cloak of Invisibility Technique \\",
    "requiredNatures": []
  },
  {
    "source": "CANON",
    "pool": "FOUNDATION",
    "slug": "tree-climbing-baumlaufen",
    "name": "Tree Climbing / Baumlaufen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Tree Climbing / Baumlaufen**                            | Chakra an den Füßen konzentrieren, um vertikale Flächen zu betreten | Academy bzw. frühes Training                                                                                                                                                      |",
    "description": "Chakra an den Füßen konzentrieren, um vertikale Flächen zu betreten",
    "role": "Academy bzw. frühes Training",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-chakra-suppression-chakra-unterdruckung",
    "name": "Basic Chakra Suppression / Chakra-Unterdrückung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Chakra Suppression / Chakra-Unterdrückung**       | Eigenen Chakrafluss reduzieren, um schwieriger aufgespürt zu werden | Stealth-/Tracking-Training                                                                                                                                                        |",
    "description": "Eigenen Chakrafluss reduzieren, um schwieriger aufgespürt zu werden",
    "role": "Stealth-/Tracking-Training",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "chakra-concentration-chakra-konzentration",
    "name": "Chakra Concentration / Chakra-Konzentration",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Chakra Concentration / Chakra-Konzentration**           | Chakra gezielt in einen Körperbereich leiten                        | Grundlage für spätere Techniken                                                                                                                                                   |",
    "description": "Chakra gezielt in einen Körperbereich leiten",
    "role": "Grundlage für spätere Techniken",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-surface-grip-oberflachenhaftung",
    "name": "Basic Surface Grip / Oberflächenhaftung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Surface Grip / Oberflächenhaftung**               | Hände oder Füße durch Chakra an einer Oberfläche halten             | Rettung/Klettern/Infiltration                                                                                                                                                     |",
    "description": "Hände oder Füße durch Chakra an einer Oberfläche halten",
    "role": "Rettung/Klettern/Infiltration",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-chakra-transfer-chakra-ubertragung",
    "name": "Basic Chakra Transfer / Chakra-Übertragung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Chakra Transfer / Chakra-Übertragung**            | Kleine Mengen Chakra kontrolliert an eine andere Person übertragen  | Support-/Medical-Einstieg                                                                                                                                                         |",
    "description": "Kleine Mengen Chakra kontrolliert an eine andere Person übertragen",
    "role": "Support-/Medical-Einstieg",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-disguise-einfache-tarnung",
    "name": "Basic Disguise / Einfache Tarnung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Disguise / Einfache Tarnung**                     | Ausrüstung, Haltung und Umgebung zur Tarnung einsetzen              | Infiltration                                                                                                                                                                      |",
    "description": "Ausrüstung, Haltung und Umgebung zur Tarnung einsetzen",
    "role": "Infiltration",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-trap-detection-fallen-erkennen",
    "name": "Basic Trap Detection / Fallen erkennen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Trap Detection / Fallen erkennen**                | Chakra/Beobachtung zur Erkennung einfacher Shinobi-Fallen           | Missionsausbildung                                                                                                                                                                |",
    "description": "Chakra/Beobachtung zur Erkennung einfacher Shinobi-Fallen",
    "role": "Missionsausbildung",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "silent-movement-lautlose-bewegung",
    "name": "Silent Movement / Lautlose Bewegung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Silent Movement / Lautlose Bewegung**                   | Grundlegende Shinobi-Technik zum geräuscharmen Bewegen              | Stealth-Training                                                                                                                                                                  |",
    "description": "Grundlegende Shinobi-Technik zum geräuscharmen Bewegen",
    "role": "Stealth-Training",
    "requiredNatures": []
  },
  {
    "source": "FOUNDATION",
    "pool": "FOUNDATION",
    "slug": "basic-chakra-sensing-chakra-wahrnehmung",
    "name": "Basic Chakra Sensing / Chakra-Wahrnehmung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **Basic Chakra Sensing / Chakra-Wahrnehmung**             | Sehr grobe Wahrnehmung deutlicher Chakra-Präsenzen                  | Einstieg für Sensor-Typen                                                                                                                                                         |",
    "description": "Sehr grobe Wahrnehmung deutlicher Chakra-Präsenzen",
    "role": "Einstieg für Sensor-Typen",
    "requiredNatures": []
  },
  {
    "source": "CANON",
    "pool": "FOUNDATION",
    "slug": "one-thousand-years-of-death-tausend-jahre-des-todes",
    "name": "One Thousand Years of Death / Tausend Jahre des Todes",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "E",
    "category": "Foundation",
    "progressionType": "FOUNDATION",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": null,
    "actionType": null,
    "range": null,
    "duration": null,
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "| **One Thousand Years of Death / Tausend Jahre des Todes** | **Kakashis Finger-in-den-Arsch-Technik                              | Persönlicher Arschbohrer der Vergeltung                                                                                                                                           |",
    "description": "**Kakashis Finger-in-den-Arsch-Technik",
    "role": "Persönlicher Arschbohrer der Vergeltung",
    "requiredNatures": []
  }
] satisfies JutsuSeedRecord[];
