import type { JutsuSeedRecord } from "./jutsu-seed-types.generated";

export const UzumakiJutsu = [
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "einfaches-aufbewahrungssiegel",
    "name": "Einfaches Aufbewahrungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": "Uzumaki-Grundausbildung oder vergleichbare",
    "chakraCost": 10,
    "chakraText": "10",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "Bis zur Freisetzung",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 1. Einfaches Aufbewahrungssiegel\n\n**Rang:** D \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 10 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** Bis zur Freisetzung \n**Herkunft:** Überliefert \n**Voraussetzung:** Uzumaki-Grundausbildung oder vergleichbare\nSiegellehre\n\nVersiegelt einen kleinen unbelebten Gegenstand in einer vorbereiteten\nSchriftrolle oder Siegelfläche. Der Gegenstand darf keine lebende\nKreatur enthalten und muss in das festgelegte Größenlimit passen.\n\n**D&D:** Ein kleiner Gegenstand kann versiegelt oder mit einer Action\nwieder freigesetzt werden. Das Siegel bleibt bestehen, bis sein Inhalt\nentnommen oder das Siegel zerstört wird.\n\n**Familientrait:** Dies ist eine geeignete erste Technik für junge\nUzumaki und kann bereits beim Akademieabschluss beherrscht werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "freisetzungszeichen",
    "name": "Freisetzungszeichen",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 5,
    "chakraText": "5",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "Sofort",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 2. Freisetzungszeichen\n\n**Rang:** D \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 5 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** Sofort \n**Herkunft:** Überliefert\n\nEin grundlegendes Zeichen zum kontrollierten Öffnen einfacher\nVersiegelungen.\n\n**D&D:** Erlaubt das Öffnen eigener D-Rang-Siegel ohne Probe. Bei\nfremden oder beschädigten einfachen Siegeln kann eine INT- oder\nChakra-Control-Probe erforderlich sein.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "siegelanalyse",
    "name": "Siegelanalyse",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Unterstützungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 10,
    "chakraText": "10",
    "actionType": "1 Action oder 1 Minute außerhalb des Kampfes",
    "range": "Berührung / 1 m",
    "duration": "Konzentration",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 3. Siegelanalyse\n\n**Rang:** D \n**Typ:** Unterstützungs-Jutsu \n**Chakra:** 10 \n**Ausführung:** 1 Action oder 1 Minute außerhalb des Kampfes \n**Reichweite:** Berührung / 1 m \n**Dauer:** Konzentration \n**Herkunft:** Überliefert\n\nDer Anwender leitet vorsichtig Chakra in ein Siegel und untersucht\ndessen Aufbau.\n\n**D&D:** Gibt Informationen über Rang, ungefähren Zweck,\nAktivierungsmechanismus und sichtbare Beschädigungen eines Siegels. Es\nentschlüsselt keine geheimen Schlüssel automatisch.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-markierung",
    "name": "Chakra-Markierung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 10,
    "chakraText": "10",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "24 Stunden",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 4. Chakra-Markierung\n\n**Rang:** D \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 10 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** 24 Stunden \n**Herkunft:** Shiogakure\n\nHinterlässt eine schwache persönliche Chakra-Signatur auf einem\nGegenstand.\n\n**D&D:** Der Anwender erkennt innerhalb kurzer Distanz, ob die eigene\nMarkierung noch vorhanden ist. Die Technik dient vor allem Ausbildung,\nBesitzmarkierung und einfachen Sicherungssystemen.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "einfaches-warnsiegel",
    "name": "Einfaches Warnsiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 15,
    "chakraText": "15",
    "actionType": "1 Minute",
    "range": "Berührung",
    "duration": "Bis ausgelöst oder entfernt",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 5. Einfaches Warnsiegel\n\n**Rang:** D \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 15 \n**Ausführung:** 1 Minute \n**Reichweite:** Berührung \n**Dauer:** Bis ausgelöst oder entfernt \n**Herkunft:** Shiogakure\n\nEin kleines Siegel reagiert, wenn eine markierte Tür, Schriftrolle oder\nKiste geöffnet wird.\n\n**D&D:** Beim Auslösen erzeugt es ein hörbares oder sichtbares\nChakra-Signal. Es verursacht keinen Schaden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "siegelstabilisierung",
    "name": "Siegelstabilisierung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "D",
    "category": null,
    "progressionType": "Unterstützungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 10,
    "chakraText": "10",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "Konzentration, bis zu 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 6. Siegelstabilisierung\n\n**Rang:** D \n**Typ:** Unterstützungs-Jutsu \n**Chakra:** 10 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** Konzentration, bis zu 1 Minute \n**Herkunft:** Rekonstruiert\n\nStabilisiert kurzfristig ein beschädigtes oder instabiles einfaches\nSiegel.\n\n**D&D:** Verhindert bei D-Rang-Siegeln vorübergehend den Zusammenbruch.\nBei stärkeren Siegeln kann es lediglich Zeit verschaffen.\n\n------------------------------------------------------------------------\n\n# C-Rang",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "groes-aufbewahrungssiegel",
    "name": "Großes Aufbewahrungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 25,
    "chakraText": "25",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "Bis zur Freisetzung",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 7. Großes Aufbewahrungssiegel\n\n**Rang:** C \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 25 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** Bis zur Freisetzung \n**Herkunft:** Überliefert\n\nEine weiterentwickelte Form des Aufbewahrungssiegels für größere\nAusrüstung, mehrere Waffen oder umfangreiche Vorräte.\n\n**D&D:** Eine Schriftrolle kann mehrere Gegenstände oder einen\nmittelgroßen unbelebten Gegenstand aufnehmen. Lebewesen können nicht\nversiegelt werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "waffen-freisetzungssiegel",
    "name": "Waffen-Freisetzungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 20,
    "chakraText": "20",
    "actionType": "Bonus Action",
    "range": "Selbst / Berührung",
    "duration": "Sofort",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 8. Waffen-Freisetzungssiegel\n\n**Rang:** C \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 20 \n**Ausführung:** Bonus Action \n**Reichweite:** Selbst / Berührung \n**Dauer:** Sofort \n**Herkunft:** Rekonstruiert\n\nEin für den Kampf optimiertes Aufbewahrungssiegel, aus dem vorbereitete\nWaffen besonders schnell freigesetzt werden können.\n\n**D&D:** Ein zuvor versiegeltes Waffenset kann als Bonus Action\ngezogen/freigesetzt werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-unterdruckungssiegel",
    "name": "Chakra-Unterdrückungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 30,
    "chakraText": "30",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 9. Chakra-Unterdrückungssiegel\n\n**Rang:** C \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 30 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** 1 Minute \n**Herkunft:** Rekonstruiert\n\nEin temporäres Siegel stört den Chakrafluss des Ziels.\n\n**D&D:** Nach erfolgreichem Treffer bzw. Anbringen muss das Ziel einen\nCON- oder Chakra-Control-Save bestehen. Bei Fehlschlag werden\nChakra-Techniken erschwert und ihre Kosten können vorübergehend steigen.\nKein vollständiger Chakra-Entzug.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "bindungssiegel",
    "name": "Bindungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 30,
    "chakraText": "30",
    "actionType": "1 Action",
    "range": "5 m / vorbereitete Fläche",
    "duration": "Konzentration, bis zu 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 10. Bindungssiegel\n\n**Rang:** C \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 30 \n**Ausführung:** 1 Action \n**Reichweite:** 5 m / vorbereitete Fläche \n**Dauer:** Konzentration, bis zu 1 Minute \n**Herkunft:** Shiogakure\n\nEin vorbereiteter Siegelkreis erzeugt Chakra-Bindungen um eine Kreatur,\ndie ihn betritt.\n\n**D&D:** Das Ziel macht einen DEX-Save. Bei Fehlschlag wird seine\nBewegung stark reduziert; mit STR oder Chakra Control kann es versuchen,\nsich zu befreien.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "schutzsiegel",
    "name": "Schutzsiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Barrieren-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 35,
    "chakraText": "35",
    "actionType": "1 Action",
    "range": "3 m",
    "duration": "Konzentration, bis zu 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 11. Schutzsiegel\n\n**Rang:** C \n**Typ:** Barrieren-Jutsu \n**Chakra:** 35 \n**Ausführung:** 1 Action \n**Reichweite:** 3 m \n**Dauer:** Konzentration, bis zu 1 Minute \n**Herkunft:** Shiogakure\n\nErzeugt eine kleine defensive Barriere um einen markierten Punkt.\n\n**D&D:** Die Barriere besitzt eigene HP und kann Angriffe abfangen, bis\nsie zerstört wird oder der Anwender die Konzentration verliert.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-speichersiegel-klein",
    "name": "Chakra-Speichersiegel -- Klein",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "C",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": null,
    "chakraText": "variabel",
    "actionType": "Ritual",
    "range": "Berührung",
    "duration": "Bis verwendet",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 12. Chakra-Speichersiegel -- Klein\n\n**Rang:** C \n**Typ:** Versiegelungs-Jutsu\n**Chakra:** variabel \n**Ausführung:** Ritual \n**Reichweite:** Berührung \n**Dauer:** Bis verwendet \n**Herkunft:** Rekonstruiert\n\nSpeichert über längere Zeit eine begrenzte Menge Chakra in einem\nvorbereiteten Siegel.\n\n**D&D:** Das gespeicherte Chakra muss vorher tatsächlich investiert\nwerden. Es kann später nur unter den festgelegten Bedingungen\nzurückgewonnen werden. Kein kostenlos erzeugtes Chakra.\n\n------------------------------------------------------------------------\n\n# B-Rang",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "funf-punkte-barriere",
    "name": "Fünf-Punkte-Barriere",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": null,
    "progressionType": "Barrieren-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 60,
    "chakraText": "60",
    "actionType": "Ritual",
    "range": "Variabel",
    "duration": "Bis deaktiviert oder zerstört",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 13. Fünf-Punkte-Barriere\n\n**Rang:** B \n**Typ:** Barrieren-Jutsu \n**Chakra:** 60 \n**Ausführung:** Ritual \n**Reichweite:** Variabel \n**Dauer:** Bis deaktiviert oder zerstört \n**Herkunft:** Shiogakure\n\nFünf miteinander verbundene Siegelpunkte bilden eine stabile\nSchutzbarriere.\n\n**D&D:** Alle fünf Punkte müssen vorbereitet werden. Solange mehrere\nKnoten bestehen, erhält die Barriere zusätzliche Widerstandskraft. Ideal\nzur Sicherung von Gebäuden, Lagern oder Missionslagern.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-fesselungssiegel",
    "name": "Chakra-Fesselungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 55,
    "chakraText": "55",
    "actionType": "1 Action",
    "range": "Berührung",
    "duration": "Konzentration, bis zu 10 Minuten",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 14. Chakra-Fesselungssiegel\n\n**Rang:** B \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 55 \n**Ausführung:** 1 Action \n**Reichweite:** Berührung \n**Dauer:** Konzentration, bis zu 10 Minuten \n**Herkunft:** Rekonstruiert\n\nEine stärkere Form der Chakra-Unterdrückung, die den Chakrafluss eines\ngefesselten oder kampfunfähigen Ziels erheblich einschränkt.\n\n**D&D:** Das Ziel erhält deutliche Nachteile auf Chakra-Control-Proben\nund kann hochrangige Jutsu nur nach erfolgreichem Save einsetzen.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "siegel-der-technikbindung",
    "name": "Siegel der Technikbindung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 60,
    "chakraText": "60",
    "actionType": "Ritual / 1 Minute",
    "range": "Berührung",
    "duration": "Variabel",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 15. Siegel der Technikbindung\n\n**Rang:** B \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 60 \n**Ausführung:** Ritual / 1 Minute \n**Reichweite:** Berührung \n**Dauer:** Variabel \n**Herkunft:** Rekonstruiert\n\nEin komplexes Siegel wird auf ein Objekt oder eine vorbereitete Fläche\ngeschrieben und mit einer bestimmten Chakra-Technik verknüpft.\n\n**D&D:** Ermöglicht vorbereitete Siegel-Fallen oder automatische\nAktivierungen. Die eingebundene Technik muss separat beherrscht und mit\nChakra gespeist werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Rekonstruiert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-ketten-erste-manifestation",
    "name": "Chakra-Ketten -- Erste Manifestation",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": null,
    "progressionType": "Ketten-Technik",
    "prerequisiteText": "Angeborene Begabung für Chakra-Ketten",
    "chakraCost": 50,
    "chakraText": "50",
    "actionType": "1 Action",
    "range": "6 m",
    "duration": "Konzentration, bis zu 1 Runde",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 16. Chakra-Ketten -- Erste Manifestation\n\n**Rang:** B \n**Typ:** Ketten-Technik \n**Chakra:** 50 \n**Ausführung:** 1 Action \n**Reichweite:** 6 m \n**Dauer:** Konzentration, bis zu 1 Runde \n**Herkunft:** Uzumaki-Blutlinie \n**Voraussetzung:** Angeborene Begabung für Chakra-Ketten\n\nDer Anwender manifestiert erstmals eine einzelne instabile Chakrakette.\n\n**D&D:** Ein Ziel kann nach erfolgreichem Angriff bzw. misslungenem Save\nkurzzeitig festgehalten werden. Die Kette besitzt nur begrenzte\nStabilität und kann noch keine mächtigen Chakra-Wesen zuverlässig\nunterdrücken.\n\n**Hinweis:** Junge Uzumaki mit entsprechender Begabung können bereits\n**Anzeichen** dieser Technik zeigen, ohne das B-Rang-Jutsu tatsächlich\nzu beherrschen.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Uzumaki-Blutlinie",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "siegelbrecher",
    "name": "Siegelbrecher",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "B",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 50,
    "chakraText": "50",
    "actionType": "1 Action / Ritual",
    "range": "Berührung",
    "duration": "Sofort",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 17. Siegelbrecher\n\n**Rang:** B \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 50 \n**Ausführung:** 1 Action / Ritual \n**Reichweite:** Berührung \n**Dauer:** Sofort \n**Herkunft:** Überliefert\n\nEine spezialisierte Methode zum gezielten Auflösen fremder\nVersiegelungen.\n\n**D&D:** Erfordert eine Chakra-Control-/INT-Probe gegen die\nSchwierigkeit des Siegels. Ein Fehlschlag kann das Siegel aktivieren\noder beschädigen.\n\n------------------------------------------------------------------------\n\n# A-Rang",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "vier-symbole-siegel",
    "name": "Vier-Symbole-Siegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 120,
    "chakraText": "120",
    "actionType": "Ritual",
    "range": "Berührung",
    "duration": "Langfristig",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 18. Vier-Symbole-Siegel\n\n**Rang:** A \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 120 \n**Ausführung:** Ritual \n**Reichweite:** Berührung \n**Dauer:** Langfristig \n**Herkunft:** Überliefert\n\nEine hochentwickelte Versiegelungstechnik, die große Mengen Chakra oder\nmächtige Entitäten innerhalb eines Trägers bzw. Gefäßes binden kann.\n\n**D&D:** Kein gewöhnliches Kampf-Jutsu. Benötigt Vorbereitung, präzise\nKontrolle und ein geeignetes Gefäß. Stärke und Stabilität hängen vom\nAnwender und Ziel ab.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "doppeltes-vier-symbole-siegel",
    "name": "Doppeltes Vier-Symbole-Siegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 200,
    "chakraText": "200",
    "actionType": "Ritual",
    "range": "Berührung",
    "duration": "Langfristig",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 19. Doppeltes Vier-Symbole-Siegel\n\n**Rang:** A \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 200 \n**Ausführung:** Ritual \n**Reichweite:** Berührung \n**Dauer:** Langfristig \n**Herkunft:** Überliefert\n\nZwei Vier-Symbole-Siegel werden miteinander kombiniert und erzeugen eine\nwesentlich komplexere Versiegelungsstruktur.\n\n**D&D:** Kann extrem große Chakraquellen langfristig einschließen und\nderen Chakrafluss kontrolliert regulieren. Die Technik erfordert\naußergewöhnliche Versiegelungskenntnisse.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "groes-chakra-unterdruckungssiegel",
    "name": "Großes Chakra-Unterdrückungssiegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 110,
    "chakraText": "110",
    "actionType": "1 Action bei vorbereitetem Siegel",
    "range": "10 m",
    "duration": "Konzentration, bis zu 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 20. Großes Chakra-Unterdrückungssiegel\n\n**Rang:** A \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 110 \n**Ausführung:** 1 Action bei vorbereitetem Siegel \n**Reichweite:** 10 m \n**Dauer:** Konzentration, bis zu 1 Minute \n**Herkunft:** Shiogakure\n\nEin großflächiges Siegel stört den Chakrafluss aller markierten Ziele\ninnerhalb seines Bereichs.\n\n**D&D:** Betroffene Kreaturen müssen Saves bestehen. Bei Fehlschlag\nwerden Chakra-Techniken erschwert und hochrangige Techniken können\nvorübergehend blockiert werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "chakra-ketten-kontrollierte-fesselung",
    "name": "Chakra-Ketten -- Kontrollierte Fesselung",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Ketten-Technik",
    "prerequisiteText": "Chakra-Ketten -- Erste Manifestation",
    "chakraCost": 100,
    "chakraText": "100",
    "actionType": "1 Action",
    "range": "12 m",
    "duration": "Konzentration, bis zu 1 Minute",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 21. Chakra-Ketten -- Kontrollierte Fesselung\n\n**Rang:** A \n**Typ:** Ketten-Technik \n**Chakra:** 100 \n**Ausführung:** 1 Action \n**Reichweite:** 12 m \n**Dauer:** Konzentration, bis zu 1 Minute \n**Herkunft:** Uzumaki-Blutlinie \n**Voraussetzung:** Chakra-Ketten -- Erste Manifestation\n\nDer Anwender kann mehrere stabile Chakraketten manifestieren und Gegner\ngleichzeitig körperlich und über ihren Chakrafluss binden.\n\n**D&D:** Mehrere Ziele können erfasst werden. Gebundene Ziele verlieren\nBewegung und erhalten starke Nachteile auf Chakra-Control-Proben.\nMächtige Ziele erhalten wiederholte Saves.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Uzumaki-Blutlinie",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "uzumaki-barrierenetz",
    "name": "Uzumaki-Barrierenetz",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Barrieren-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 130,
    "chakraText": "130",
    "actionType": "Ritual",
    "range": "Großer Bereich",
    "duration": "Bis aufgehoben",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 22. Uzumaki-Barrierenetz\n\n**Rang:** A \n**Typ:** Barrieren-Jutsu \n**Chakra:** 130 \n**Ausführung:** Ritual \n**Reichweite:** Großer Bereich \n**Dauer:** Bis aufgehoben \n**Herkunft:** Shiogakure\n\nEin Netzwerk miteinander verbundener Versiegelungspunkte schützt ein\ngrößeres Gebiet und registriert Störungen im Chakrafluss.\n\n**D&D:** Geeignet zur Sicherung eines Anwesens, Bezirks oder wichtigen\nDorfbereichs. Mehrere Anwender können Chakra zur Stabilisierung\nbeitragen.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "lebenskraft-siegel",
    "name": "Lebenskraft-Siegel",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "A",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu / Unterstützungs-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 120,
    "chakraText": "120",
    "actionType": "Ritual",
    "range": "Berührung",
    "duration": "Variabel",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 23. Lebenskraft-Siegel\n\n**Rang:** A \n**Typ:** Versiegelungs-Jutsu / Unterstützungs-Jutsu \n**Chakra:** 120 \n**Ausführung:** Ritual \n**Reichweite:** Berührung \n**Dauer:** Variabel \n**Herkunft:** Shiogakure\n\nEin gefährliches Siegel nutzt die außergewöhnliche Lebenskraft des\nAnwenders als zusätzliche Energiequelle.\n\n**D&D:** Der Anwender kann HP opfern, um ein Siegel zu verstärken oder\naufrechtzuerhalten. Die verlorenen HP können nicht durch einen normalen\nShort Rest sofort zurückgewonnen werden.\n\n------------------------------------------------------------------------\n\n# S-Rang",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "adamantine-sealing-chains",
    "name": "Adamantine Sealing Chains",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Ketten-Technik",
    "prerequisiteText": "Außergewöhnliche angeborene Begabung und vollständige",
    "chakraCost": 250,
    "chakraText": "250",
    "actionType": "1 Action",
    "range": "20 m",
    "duration": "Konzentration",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 24. Adamantine Sealing Chains\n\n**Rang:** S \n**Typ:** Ketten-Technik \n**Chakra:** 250 \n**Ausführung:** 1 Action \n**Reichweite:** 20 m \n**Dauer:** Konzentration \n**Herkunft:** Uzumaki-Blutlinie \n**Voraussetzung:** Außergewöhnliche angeborene Begabung und vollständige\nBeherrschung der Chakra-Ketten\n\nDie höchste bekannte Form der Uzumaki-Chakraketten. Mehrere extrem\nwiderstandsfähige Ketten können mächtige Gegner fesseln und deren Chakra\nunterdrücken.\n\n**D&D:** Kann mehrere Ziele binden. Die Ketten besitzen eigene\nWiderstandskraft und unterdrücken den Chakrafluss gebundener Kreaturen\nerheblich. Selbst extrem starke Chakra-Wesen können eingeschränkt\nwerden, erhalten jedoch entsprechende Saves und Möglichkeiten zum\nAusbruch.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Uzumaki-Blutlinie",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "adamantine-sealing-chains-barriere",
    "name": "Adamantine Sealing Chains -- Barriere",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Ketten-Technik / Barrieren-Jutsu",
    "prerequisiteText": "Adamantine Sealing Chains",
    "chakraCost": 300,
    "chakraText": "300",
    "actionType": "1 Action",
    "range": "20 m Radius",
    "duration": "Konzentration",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 25. Adamantine Sealing Chains -- Barriere\n\n**Rang:** S \n**Typ:** Ketten-Technik / Barrieren-Jutsu \n**Chakra:** 300 \n**Ausführung:** 1 Action \n**Reichweite:** 20 m Radius \n**Dauer:** Konzentration \n**Herkunft:** Uzumaki-Blutlinie \n**Voraussetzung:** Adamantine Sealing Chains\n\nDie manifestierten Ketten werden zu einer geschlossenen Barriere\nverwoben.\n\n**D&D:** Erzeugt eine extrem widerstandsfähige Barriere. Das\nAufrechterhalten verursacht hohe Chakrakosten und bindet die\nKonzentration des Anwenders vollständig.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Uzumaki-Blutlinie",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "acht-trigramme-versiegelungsstil",
    "name": "Acht-Trigramme-Versiegelungsstil",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": "Meisterschaft des Vier-Symbole-Siegels",
    "chakraCost": 300,
    "chakraText": "300+",
    "actionType": "Großes Ritual",
    "range": "Berührung",
    "duration": "Permanent / bis gebrochen",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 26. Acht-Trigramme-Versiegelungsstil\n\n**Rang:** S \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 300+ \n**Ausführung:** Großes Ritual \n**Reichweite:** Berührung \n**Dauer:** Permanent / bis gebrochen \n**Herkunft:** Überliefert \n**Voraussetzung:** Meisterschaft des Vier-Symbole-Siegels\n\nEine Meistertechnik, bei der komplexe Versiegelungsstrukturen\nmiteinander kombiniert werden, um enorme Chakraquellen dauerhaft in\neinem lebenden Träger zu binden und deren Chakra kontrolliert\ndurchsickern zu lassen.\n\n**D&D:** Story-/Ritualtechnik. Nicht als gewöhnliche Combat Action\ngedacht. Durchführung und Folgen sollten vom DM abhängig vom Ziel\nfestgelegt werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "uzumaki-grobarriere",
    "name": "Uzumaki-Großbarriere",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Barrieren-Jutsu",
    "prerequisiteText": null,
    "chakraCost": 350,
    "chakraText": "350+",
    "actionType": "Großes Ritual",
    "range": "Dorf-/Festungsbereich",
    "duration": "Solange gespeist",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 27. Uzumaki-Großbarriere\n\n**Rang:** S \n**Typ:** Barrieren-Jutsu \n**Chakra:** 350+ \n**Ausführung:** Großes Ritual \n**Reichweite:** Dorf-/Festungsbereich \n**Dauer:** Solange gespeist \n**Herkunft:** Shiogakure\n\nDie höchste auf Shio no Kuni entwickelte defensive Versiegelung der\nFamilie. Zahlreiche Siegelknoten werden zu einer großflächigen Barriere\nverbunden.\n\n**D&D:** Mehrere Shinobi können Chakra einspeisen. Die Barriere kann\nAngriffe abfangen, Eindringlinge registrieren und beschädigte Bereiche\ndurch andere Knoten teilweise kompensieren. Für normalen Einzelkampf\nungeeignet.\n\n------------------------------------------------------------------------\n\n# Verbotene Uzumaki-Techniken",
    "traditionProvenance": "Shiogakure",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "reaper-death-seal",
    "name": "Reaper Death Seal",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": "Meisterhafte Versiegelungskenntnisse",
    "chakraCost": 300,
    "chakraText": "300+ und besonderer Preis",
    "actionType": "Ritual / Kampfhandlung",
    "range": "Nahbereich",
    "duration": "Permanent",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 28. Reaper Death Seal\n\n**Rang:** S / Verboten \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 300+ und besonderer Preis \n**Ausführung:** Ritual / Kampfhandlung \n**Reichweite:** Nahbereich \n**Dauer:** Permanent \n**Herkunft:** Überliefert \n**Voraussetzung:** Meisterhafte Versiegelungskenntnisse\n\nEine extrem gefährliche Versiegelungstechnik, bei der der Anwender eine\nübernatürliche Entität zur Versiegelung der Seele des Ziels heranzieht.\n\n**D&D:** Diese Technik besitzt keinen gewöhnlichen Chakra-Preis allein.\nIhre Anwendung fordert einen fundamentalen Preis vom Anwender und sollte\nausschließlich als Story-/Limit-Break-Technik eingesetzt werden.\n\n------------------------------------------------------------------------",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  },
  {
    "source": "SHIO_HOMEBREW",
    "pool": "UZUMAKI",
    "slug": "dead-demon-consuming-seal-release",
    "name": "Dead Demon Consuming Seal: Release",
    "germanName": null,
    "englishName": null,
    "japaneseName": null,
    "rank": "S",
    "category": null,
    "progressionType": "Versiegelungs-Jutsu",
    "prerequisiteText": "Kenntnis des Reaper Death Seal und entsprechendes",
    "chakraCost": 200,
    "chakraText": "200+ und besonderer Preis",
    "actionType": "Ritual",
    "range": "Selbst",
    "duration": "Sofort",
    "saveAbility": null,
    "damage": null,
    "attackType": null,
    "natures": [],
    "rawMarkdown": "## 29. Dead Demon Consuming Seal: Release\n\n**Rang:** S / Verboten \n**Typ:** Versiegelungs-Jutsu \n**Chakra:** 200+ und besonderer Preis \n**Ausführung:** Ritual \n**Reichweite:** Selbst \n**Dauer:** Sofort \n**Herkunft:** Überliefert \n**Voraussetzung:** Kenntnis des Reaper Death Seal und entsprechendes\nRitualwissen\n\nEine Methode, mit der im Reaper Death Seal gebundene Seelen wieder\nfreigesetzt werden können.\n\n**D&D:** Reine Storytechnik. Die Anwendung hat extreme körperliche\nKonsequenzen und benötigt die passenden rituellen Voraussetzungen.\n\n------------------------------------------------------------------------\n\n# Lernprogression für junge Uzumaki\n\nEin typischer Ausbildungsweg innerhalb der Familie könnte folgendermaßen\naussehen:\n\n  -----------------------------------------------------------------------\n  Stufe                               Typische Kenntnisse\n  ----------------------------------- -----------------------------------\n  **Akademie / Genin-Anfang**         Siegelanalyse, Freisetzungszeichen,\n                                      Einfaches Aufbewahrungssiegel\n\n  **Erfahrener Genin**                Warnsiegel, Siegelstabilisierung,\n                                      erste C-Rang-Grundlagen\n\n  **Chūnin**                          größere Aufbewahrung, Bindungs- und\n                                      Unterdrückungssiegel, Barrieren\n\n  **Erfahrener Chūnin / Jōnin**       komplexe B-Rang-Siegel,\n                                      Siegelbrechen, Chakra-Speicherung\n\n  **Jōnin / Spezialist**              A-Rang-Versiegelungen und\n                                      großflächige Barrieren\n\n  **Meister**                         S-Rang-Rituale und außergewöhnliche\n                                      Uzumaki-Techniken\n  -----------------------------------------------------------------------\n\n## Sora und Yuna\n\n**Sora Uzumaki** und **Yuna Uzumaki** beginnen ihre Laufbahn mit zehn\nJahren.\n\nBeide besitzen familiär vermittelte Grundlagen der Siegellehre. Für\nihren Start bietet sich jeweils **eine D-Rang-Familientechnik** als\ntatsächlich beherrschtes Jutsu an.\n\nWeitere Uzumaki-Techniken können sie bereits aus Unterricht und\nFamilientraining kennen, ohne sie selbst zuverlässig einsetzen zu\nkönnen.\n\nOb Sora oder Yuna eine Begabung für die Chakra-Ketten besitzt, wird erst\nbei der individuellen Charaktererstellung festgelegt.\n\n------------------------------------------------------------------------\n\n# DM-Hinweise\n\n-   **Kenntnis ≠ Beherrschung.** Ein Genin darf wissen, wie ein\n    A-Rang-Siegel grundsätzlich funktioniert, ohne es ausführen zu\n    können.\n-   Uzumaki-Familientechniken können über **Training mit Verwandten,\n    Schriftrollen, Missionen und persönliche Entwicklung**\n    freigeschaltet werden.\n-   Die angegebenen Chakrakosten sind Ausgangswerte und können beim\n    Balancing des gesamten Jutsu-Katalogs angepasst werden.\n-   S-Rang-Versiegelungen sind überwiegend **Story- und\n    Ritualtechniken** und sollten nicht wie gewöhnliche Combat-Spells\n    behandelt werden.\n-   Chakra-Ketten sind eine **besondere Begabung**, kein automatisches\n    Merkmal jedes Uzumaki.",
    "traditionProvenance": "Überliefert",
    "requiredNatures": []
  }
] satisfies JutsuSeedRecord[];
